[package_fields]
spec_file = "hello-world-nim.sss"
package_name = "hello-world-nim"
version_number = "1.0.0"
revision_number = "1"
homepage="https://github.com/eth-pkg/pkg-builder#examples"


[package_type]
package_type="default"
tarball_url = "hello-world-nim-1.0.0.tar.gz"
tarball_hash="b24e4ff701d8cbccab0cc78f2de55518babcd05a861af8d5d140863637b0ec74ba3ed5255bafc7fbe596defcc227e8f788c1e540655725eeabb7144be573e8a7"

[package_type.language_env]
language_env = "nim"
nim_version = "2.0.2"
nim_binary_url = "https://nim-lang.org/download/nim-2.0.2-linux_x64.tar.xz"
nim_version_checksum = "047dde8ff40b18628ac1188baa9ca992d05f1f45c5121d1d07a76224f06e1551  nim-2.0.2-linux_x64.tar.xz"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.2.7"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/bookworm"
