[package_fields]
spec_file = "hello-world-typescript.sss"
package_name = "hello-world-typescript"
version_number = "1.0.0"
revision_number = "1"
homepage="https://github.com/eth-pkg/pkg-builder#examples"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "hello-world-typescript-1.0.0.tar.gz"
tarball_hash = "e28af9271dd941888317597af77246c14671c83254a06c756d5fc56f0291a411e89fb730c1d19a848b3c3ac185c0ba20ed1accdd5feb6cc2a1c1c3a2febeba5c"

[package_type.language_env]
language_env = "javascript"
node_version = "20.12.2"
node_binary_url = "https://nodejs.org/download/release/v20.12.2/node-v20.12.2-linux-x64.tar.gz"
node_binary_checksum = "f8f9b6877778ed2d5f920a5bd853f0f8a8be1c42f6d448c763a95625cbbb4b0d"
yarn_version = "1.22.19"

[build_env]
codename="noble numbat"
arch = "amd64"
pkg_builder_version="0.2.3"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.20"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/noble"
