
[workspace]
members = [
    "crates/config",
    "crates/cli",
    "crates/makefile",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
clap = { version = "4.5.4", features = ["derive"] }
toml = "0.8.12"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4"
thiserror = "1.0"
shellexpand = "3.1.0"
tempfile = "3.1"
sha1 = "0.11.0-pre.3"
semver = "1.0.20"
url = "2.4.1"

# Local crates
pkg-builder-config = { path = "crates/config" }
pkg-builder-makefile = { path = "crates/makefile" }
