[package]
name = "types"
version = "0.1.0"
edition = "2021"

[lib]
name = "types"
path = "src/mod.rs"  

[dependencies]
toml = { workspace = true}
serde ={ workspace = true}
thiserror = { workspace = true}
