[package]
name = "types"
version = "0.1.0"
edition = "2021"

[lib]
name = "types"
path = "src/mod.rs"  

[dependencies]
toml = "0.8.12"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
