[package]
name = "test-virtual-package"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "test-virtual-package.sss"

[source]
type = "virtual"

[build]
distribution = "noble numbat"
arch = "amd64"
workdir = "~/.pkg-builder/packages/noble"

[testing]
lintian = true
piuparts = true

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.20"

[verify]
package_hash = [
    { name = "test-virtual-package_1.0.0-1.dsc", hash = "0d600a16add6cba8ab8e62dfff2a3919a5d33e46" },
    { name = "test-virtual-package_1.0.0-1_amd64.deb", hash = "a8dfd77d17b659443a091e7473d4a96b06b9ee16" },
]
