[package]
name = "test-virtual-package"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "test-virtual-package.sss"

[source]
type = "virtual"

[build]
distribution = "noble numbat"
arch = "amd64"
workdir = "~/.pkg-builder/packages/noble"

[testing]
lintian = true
piuparts = true

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.20"

[verify]
package_hash = [
    { name = "test-virtual-package_1.0.0-1.dsc", hash = "6a8057455e9bbc2a4ef2687422aa1106fe879244edf6fb43f15e76e13b3b3898" },
    { name = "test-virtual-package_1.0.0-1_amd64.deb", hash = "8d46b37d27024e5747158990440140eea3c4e805ef97a87bc647b39ba7e65800" },
]
