[package]
name = "test-virtual-package"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "test-virtual-package.sss"

[source]
type = "virtual"

[build]
distribution = "noble numbat"
arch = "amd64"
workdir = "~/.pkg-builder/packages/noble"

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"

[verify]
package_hash = [
    { name = "test-virtual-package_1.0.0-1.dsc", hash = "8ca174829ea2e72a650007cfcfe9fb07cd20cc8fdfcbaac2a58b198f78632acd" },
    { name = "test-virtual-package_1.0.0-1_amd64.deb", hash = "2c519f82ac82c53790e7aa6bea365864aefc28d4e33cadd374b41cfa98fc1878" },
]
