[package]
name = "test-virtual-package"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "test-virtual-package.sss"

[source]
type = "virtual"

[build]
distribution = "trixie"
arch = "amd64"
workdir = "~/.pkg-builder/packages/trixie"

[testing]
lintian = true
piuparts = true

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.28"

[verify]
package_hash = [
    { name = "test-virtual-package_1.0.0-1.dsc", hash = "3ed6c569e9a1b1a0e14bd16eca323a72e534668c" },
    { name = "test-virtual-package_1.0.0-1_amd64.deb", hash = "9230abc248a2f9fd212796d1e60486a11175acf5" },
]
