[package_fields]
spec_file = "hello-world-python.sss"
package_name = "hello-world-python"
version_number = "1.0.0"
revision_number = "1"
homepage="https://github.com/eth-pkg/pkg-builder#examples"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "hello-world-1.0.0.tar.gz"
tarball_hash = "1915a59fabb5859cfd4c14eb2cde7064acf3b9ff6e9e78fa68ed06f4acc482b5"

[package_type.language_env]
language_env = "python"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.2.8"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/bookworm"