[package]
name = "pkg-builder-cli"
version = "0.4.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "pkg-builder"
path = "src/main.rs"

[dependencies]
pkg-builder-config = { path = "../config" }
pkg-builder-init = { path = "../init" }
pkg-builder-makefile = { path = "../makefile" }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
dialoguer = { workspace = true }
