[package]
name = "test-virtual-package"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "test-virtual-package.sss"

[source]
type = "virtual"

[build]
distribution = "bookworm"
arch = "amd64"
workdir = "~/.pkg-builder/packages/bookworm"

[testing]
lintian = true
piuparts = true

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.28"

[verify]
package_hash = [
    { name = "test-virtual-package_1.0.0-1.dsc", hash = "480fbcb7d6847e4a286f287c4ed9b5f6237a2834" },
    { name = "test-virtual-package_1.0.0-1_amd64.deb", hash = "23dc4a25051558150ee5d0c0775e56114a667a5e" },
]
