[package]
name = "test-virtual-package"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec_file = "test-virtual-package.sss"

[source]
type = "virtual"

[build]
distribution = "bookworm"
arch = "amd64"
workdir = "~/.pkg-builder/packages/bookworm"

[testing]
lintian = true
piuparts = true

[tools]
pkg_builder = "0.3.1"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.28"
