[package]
name = "test-virtual-package"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "test-virtual-package.sss"

[source]
type = "virtual"

[build]
distribution = "bookworm"
arch = "amd64"
workdir = "~/.pkg-builder/packages/bookworm"

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"

[verify]
package_hash = [
    { name = "test-virtual-package_1.0.0-1.dsc", hash = "8afb82972b8536623a794177ed591b5a8301a770ad1ce9869645eef31bcfd349" },
    { name = "test-virtual-package_1.0.0-1_amd64.deb", hash = "d98b41e1e1163ebd2d8f2a2483a9892256759f47c1095ab28fe29ba280ce60e0" },
]
