#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which hello-world)"
  assertEquals "/usr/bin/hello-world" "$output"
}

test_invocation_with_dotnet(){
  output="$(hello-world)"
  assertContains "Hello, World!" "$output"
}

. shunit2