[package]
name = "hello-world-python"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec_file = "hello-world-python.sss"

[source]
type = "tarball"
url = "hello-world-1.0.0.tar.gz"
hash = "1915a59fabb5859cfd4c14eb2cde7064acf3b9ff6e9e78fa68ed06f4acc482b5"

[build]
distribution = "trixie"
arch = "amd64"
workdir = "~/.pkg-builder/packages/trixie"

[testing]
lintian = true
piuparts = true
autopkgtest = true

[tools]
pkg_builder = "0.3.1"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.28"
