[package]
name = "pkg-builder-pipeline"
version = "0.4.0"
edition = "2021"

[lib]
name = "pipeline"
path = "src/lib.rs"

[dependencies]
pkg-builder-config = { path = "../config" }
pkg-builder-tool = { path = "../tool" }
pkg-builder-debcrafter = { path = "../debcrafter" }
pkg-builder-runtime = { path = "../runtime" }
log = { workspace = true }
thiserror = { workspace = true }
dirs = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
sha1 = { workspace = true }
shellexpand = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
