[package]
name = "hello-world-go"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec_file = "hello-world-go.sss"

[source]
type = "tarball"
url = "hello-world-go-1.0.0.tar.gz"
hash = "c268da86e5489a61491313aac237baf895cf269da477cbe9dc8bf4afdf0847a52b4d15ffb763f2f3ea6022116e3ce44df25384522fbdd40dd79a3a84252640cb"

[build]
distribution = "noble numbat"
arch = "amd64"
workdir = "~/.pkg-builder/packages/noble"

[runtime]
recipe = "go"
binary_url = "https://go.dev/dl/go1.22.2.linux-amd64.tar.gz"
binary_checksum = "5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17"

[testing]
lintian = true
piuparts = true
autopkgtest = true

[tools]
pkg_builder = "0.3.1"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.20"
