use config::PkgConfig;

use crate::chroot_setup::ChrootSetup;

/// Generate a Perl sbuild.conf file from config + chroot setup.
pub fn render_sbuild_conf(config: &PkgConfig, setup: &ChrootSetup) -> String {
    let mut out = String::new();

    // Header
    let runtime_label = config
        .runtime
        .as_ref()
        .map(|rt| rt.profile.as_str())
        .unwrap_or("none");
    out.push_str(&format!(
        "# Auto-generated by pkg-builder — do not edit\n\
         # Runtime: {} | Distribution: {}\n\n",
        runtime_label,
        config.build_env.distribution.as_short()
    ));

    // Basic settings
    out.push_str(&format!(
        "$distribution = '{}';\n",
        config.build_env.distribution.as_short()
    ));
    out.push_str("$build_arch_all = 1;\n");
    out.push_str("$build_source = 1;\n");
    out.push_str("$source_only_changes = 1;\n");
    out.push_str("$chroot_mode = 'unshare';\n");
    out.push_str("$run_piuparts = 0;\n");
    out.push_str("$apt_upgrade = 0;\n");
    out.push_str("$apt_distupgrade = 0;\n");
    out.push_str("$run_autopkgtest = 0;\n");
    out.push_str("$verbose = 1;\n");
    out.push_str("$run_lintian = 0;\n");

    // Build dir — use $ENV{HOME} so the path isn't tied to a specific user
    let build_dir = portabilize_perl_path(&format!(
        "{}/{}-{}-{}",
        config.build_env.workdir.display(),
        config.package.name,
        config.package.version,
        config.package.revision
    ));
    out.push_str(&format!("$build_dir = {};\n", build_dir));
    out.push('\n');

    // Runtime Perl code (variable declarations + @runtime_commands)
    if let Some(ref perl_code) = setup.runtime_perl {
        out.push_str(perl_code);
        if !perl_code.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }

    // Assemble $external_commands
    let has_pre = !setup.pre_runtime_commands.is_empty();
    let has_runtime = setup.runtime_perl.is_some();
    let has_post = !setup.post_runtime_commands.is_empty();

    if has_pre || has_runtime || has_post {
        out.push_str("$external_commands = {\n");
        out.push_str("    'chroot-setup-commands' => [\n");

        for cmd in &setup.pre_runtime_commands {
            out.push_str(&format!("        {},\n", perl_quote(cmd)));
        }

        if has_runtime {
            out.push_str("        @runtime_commands,\n");
        }

        for cmd in &setup.post_runtime_commands {
            out.push_str(&format!("        {},\n", perl_quote(cmd)));
        }

        out.push_str("    ],\n");
        out.push_str("};\n");
    }

    // Perl config files must return a true value
    out.push_str("\n1;\n");

    out
}

/// Quote a string for use in a Perl single-quoted context.
fn perl_quote(s: &str) -> String {
    if !s.contains('\'') {
        format!("'{}'", s)
    } else if !s.contains('}') || balanced_braces(s) {
        format!("q{{{}}}", s)
    } else {
        let escaped = s
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('$', "\\$")
            .replace('@', "\\@");
        format!("\"{}\"", escaped)
    }
}

/// Convert an absolute path to a portable Perl expression.
fn portabilize_perl_path(path: &str) -> String {
    if let Ok(home) = std::env::var("HOME") {
        if let Some(rest) = path.strip_prefix(&home) {
            let rest = rest.strip_prefix('/').unwrap_or(rest);
            return format!("\"$ENV{{HOME}}/{}\"", rest);
        }
    }
    format!("'{}'", path)
}

fn balanced_braces(s: &str) -> bool {
    let mut depth = 0i32;
    for c in s.chars() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth < 0 {
                    return false;
                }
            }
            _ => {}
        }
    }
    depth == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_perl_quote_simple() {
        assert_eq!(perl_quote("hello"), "'hello'");
        assert_eq!(perl_quote("apt install -y wget"), "'apt install -y wget'");
    }

    #[test]
    fn test_perl_quote_with_single_quotes() {
        let cmd = r#"echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99snapshot"#;
        let quoted = perl_quote(cmd);
        assert!(quoted.starts_with("q{"));
    }

    #[test]
    fn test_balanced_braces() {
        assert!(balanced_braces("hello"));
        assert!(balanced_braces("{hello}"));
        assert!(balanced_braces("{{}}"));
        assert!(!balanced_braces("{"));
        assert!(!balanced_braces("}"));
    }
}
