[verify]
package_hash=[
    { hash="f9ed8bee7b32b1fe746c2e1acec02db5f90b9e02", name= "hello-world-java-gradle_1.0.0-1.dsc"},
    { hash="eef991395fabb27016cc1a2e37cbaa04fd869de8", name= "hello-world-java-gradle_1.0.0.orig.tar.gz"},
    { hash="1b035806a9b973e6bc71b9f67dae52358823a890", name= "hello-world-java-gradle_1.0.0-1.debian.tar.xz"},
    { hash="755070dab0ad57126a14dbb5ecbd59de725a00e9", name= "hello-world-java-gradle_1.0.0-1_amd64.deb"},
]