[package]
name = "hello-world-java-gradle"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec_file = "hello-world-java-gradle.sss"

[source]
type = "tarball"
url = "hello-world-java-gradle-1.0.0.tar.gz"
hash = "9838986aeb5fbf1e24fc20da08772c2264b5e0ace8a09b423c39cdc8774b0c04"

[build]
distribution = "noble numbat"
arch = "amd64"
workdir = "~/.pkg-builder/packages"

[runtime]
recipe = "java-gradle"
binary_url = "https://download.oracle.com/java/17/archive/jdk-17.0.10_linux-x64_bin.tar.gz"
binary_checksum = "e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"
gradle_binary_url = "https://github.com/gradle/gradle-distributions/releases/download/v8.7.0/gradle-8.7-bin.zip"
gradle_binary_checksum = "544c35d6bd849ae8a5ed0bcea39ba677dc40f49df7d1835561582da2009b961d"

[testing]
lintian = true
piuparts = true
autopkgtest = true

[tools]
pkg_builder = "0.3.1"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.20"
