[package_fields]
spec_file = "hello-world-dotnet.sss"
package_name = "hello-world-dotnet"
version_number = "1.0.0"
revision_number = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"

[package_type]
# virtual | git | default
package_type = "default"
tarball_url = "hello-world-dotnet-1.0.0.tar.gz"
tarball_hash = "f263892f5ed6cbcd82f31d60058eed359686d7e745c3da97fea917ee2f44867c4db9bd374f224e89e6efc7ffad4eadb244eefe7c95d25983f8a5a4086dadb78d"

[package_type.language_env]
language_env = "dotnet"
# Because MS force pushes the security update onto packages, without using revision numbers
dotnet_packages = [
    { name = "netstandard-targeting-pack-2.1_2.1.0-1_amd64", hash = "c849f17d5e8cdce4b068e2897939be7de4b839d3", url = "http://backup.eth-nodes.com/20240529/netstandard-targeting-pack-2.1_2.1.0-1_amd64.deb" },
    { name = "dotnet-apphost-pack-8.0_8.0.5-1_amd64", hash = "18b0d4bed3b62495564c18a6d1c30181c33831b4", url = "http://backup.eth-nodes.com/20240529/dotnet-apphost-pack-8.0_8.0.5-1_amd64.deb" },
    { name = "dotnet-targeting-pack-8.0_8.0.5-1_amd64", hash = "2727152580762a636e62f9c490c19e18339401a9", url = "http://backup.eth-nodes.com/20240529/dotnet-targeting-pack-8.0_8.0.5-1_amd64.deb" },
    { name = "dotnet-runtime-deps-8.0_8.0.5-1_amd64", hash="1f7f67a6fef920983ab2243c1c660d08e228cedf", url="http://backup.eth-nodes.com/20240529/dotnet-runtime-deps-8.0_8.0.5-1_amd64.deb"},
    { name = "dotnet-host_8.0.5-1_amd64", hash="87414e005e39785e1ba32ce8cca97878ca4c6828", url="http://backup.eth-nodes.com/20240529/dotnet-host_8.0.5-1_amd64.deb"}, 
    { name = "dotnet-hostfxr-8.0_8.0.5-1_amd64", hash="e1ec0e6b838dabfb5b47ae1b15706026996d6a7c", url="http://backup.eth-nodes.com/20240529/dotnet-hostfxr-8.0_8.0.5-1_amd64.deb"},
    { name = "dotnet-runtime-8.0_8.0.5-1_amd64", hash = "8d2443146631a861ade47a184a5b44446c6b636d", url = "http://backup.eth-nodes.com/20240529/dotnet-runtime-8.0_8.0.5-1_amd64.deb" },
    { name = "aspnetcore-targeting-pack-8.0_8.0.5-1_amd64", hash="4b6bcf15e50db2d177e6e0298a72eeae7c43d2a3", url="http://backup.eth-nodes.com/20240529/aspnetcore-targeting-pack-8.0_8.0.5-1_amd64.deb"},
    { name = "aspnetcore-runtime-8.0_8.0.5-1_amd64", hash = "7676b5b02bbc37393089418e8a03320b10e914fd", url = "http://backup.eth-nodes.com/20240529/aspnetcore-runtime-8.0_8.0.5-1_amd64.deb"},
    { name = "dotnet-sdk-8.0_8.0.204-1_amd64", hash = "a94237cb852aae05b67a5c8428a6c4f9cfb4beaa", url = "http://backup.eth-nodes.com/20240529/dotnet-sdk-8.0_8.0.204-1_amd64.deb" },
]
use_backup_version = true

[build_env]
codename = "jammy jellyfish"
arch = "amd64"
pkg_builder_version = "0.3.1"
debcrafter_version = "8189263"
run_lintian = true
run_piuparts = true
run_autopkgtest = true
lintian_version = "2.116.3"
piuparts_version = "1.1.7"
autopkgtest_version = "5.20"
sbuild_version = "0.85.6"
# package directory
workdir = "~/.pkg-builder/packages/jammy"


[verify]
# if tarball_url is specified
tarball_hash = ""
# if git_source is specified and package_is_git
git_commit = ""
# output hash
bin_bash = ""
