[package]
name = "pkg-builder"
version = "0.3.0"
edition = "2024"
build = "src/build.rs"

[[bin]]
name = "pkg-builder"
path = "src/main.rs"


[build-dependencies]
thiserror = { workspace =  true }
serde = { workspace = true }
toml = { workspace = true }

[dependencies]
cli = { workspace =  true }