# Runtime: Java with Gradle
SBUILD_FLAGS += --chroot-setup-commands='apt install -y wget'
SBUILD_FLAGS += --chroot-setup-commands='mkdir -p /opt/lib/jvm/jdk-$(JDK_VERSION)-oracle && mkdir -p /usr/lib/jvm'
SBUILD_FLAGS += --chroot-setup-commands='wget -q -O /tmp/jdk.tar.gz $(BINARY_URL)'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && echo "$(BINARY_CHECKSUM) jdk.tar.gz" >>hash_file.txt && cat hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && sha256sum -c hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && tar -zxf jdk.tar.gz -C /opt/lib/jvm/jdk-$(JDK_VERSION)-oracle --strip-components=1 && rm -f jdk.tar.gz hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='ln -s /opt/lib/jvm/jdk-$(JDK_VERSION)-oracle/bin/java /usr/bin/java'
SBUILD_FLAGS += --chroot-setup-commands='ln -s /opt/lib/jvm/jdk-$(JDK_VERSION)-oracle/bin/javac /usr/bin/javac'
SBUILD_FLAGS += --chroot-setup-commands='java -version'
SBUILD_FLAGS += --chroot-setup-commands='apt remove -y wget'
# Gradle
SBUILD_FLAGS += --chroot-setup-commands='apt install -y wget unzip'
SBUILD_FLAGS += --chroot-setup-commands='mkdir -p /opt/lib/gradle-$(GRADLE_VERSION)'
SBUILD_FLAGS += --chroot-setup-commands='wget -q -O /tmp/gradle.tar.gz $(GRADLE_BINARY_URL)'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && echo "$(GRADLE_BINARY_CHECKSUM) gradle.tar.gz" > hash_file.txt && cat hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && sha256sum -c hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && unzip gradle.tar.gz && rm -f gradle.tar.gz hash_file.txt && mv gradle-$(GRADLE_VERSION) /opt/lib'
SBUILD_FLAGS += --chroot-setup-commands='ln -s /opt/lib/gradle-$(GRADLE_VERSION)/bin/gradle /usr/bin/gradle'
SBUILD_FLAGS += --chroot-setup-commands='gradle -version'
SBUILD_FLAGS += --chroot-setup-commands='apt remove -y wget'
