# Runtime: Nim
SBUILD_FLAGS += --chroot-setup-commands='apt install -y wget'
SBUILD_FLAGS += --chroot-setup-commands='rm -rf /tmp/nim-$(NIM_VERSION) && rm -rf /usr/lib/nim/nim-$(NIM_VERSION) && rm -rf /opt/lib/nim/nim-$(NIM_VERSION) && mkdir /tmp/nim-$(NIM_VERSION)'
SBUILD_FLAGS += --chroot-setup-commands='mkdir -p /opt/lib/nim && mkdir -p /usr/lib/nim'
SBUILD_FLAGS += --chroot-setup-commands='wget -q -O /tmp/nim-$(NIM_VERSION)-linux_x64.tar.xz $(BINARY_URL)'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && echo "$(BINARY_CHECKSUM)" >> hash_file.txt && cat hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && sha256sum -c hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && tar xJf nim-$(NIM_VERSION)-linux_x64.tar.xz -C nim-$(NIM_VERSION) --strip-components=1 && rm -f nim-$(NIM_VERSION)-linux_x64.tar.xz hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && mv nim-$(NIM_VERSION) /opt/lib/nim'
SBUILD_FLAGS += --chroot-setup-commands='ln -s /opt/lib/nim/nim-$(NIM_VERSION)/bin/nim /usr/bin/nim'
SBUILD_FLAGS += --chroot-setup-commands='nim --version'
SBUILD_FLAGS += --chroot-setup-commands='apt remove -y wget'
