# Runtime: Node.js
SBUILD_FLAGS += --chroot-setup-commands='apt install -y wget'
SBUILD_FLAGS += --chroot-setup-commands='wget -q -O /tmp/node.tar.gz $(BINARY_URL)'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && echo "$(BINARY_CHECKSUM) node.tar.gz" >> hash_file.txt && cat hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && sha256sum -c hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && rm -rf /usr/share/node && mkdir /usr/share/node && tar -C /usr/share/node -xzf node.tar.gz --strip-components=1 && rm -f node.tar.gz hash_file.txt'
SBUILD_FLAGS += --chroot-setup-commands='ls -l /usr/share/node/bin'
SBUILD_FLAGS += --chroot-setup-commands='ln -s /usr/share/node/bin/node /usr/bin/node'
SBUILD_FLAGS += --chroot-setup-commands='ln -s /usr/share/node/bin/npm /usr/bin/npm'
SBUILD_FLAGS += --chroot-setup-commands='ln -s /usr/share/node/bin/npx /usr/bin/npx'
SBUILD_FLAGS += --chroot-setup-commands='ln -s /usr/share/node/bin/corepack /usr/bin/corepack'
SBUILD_FLAGS += --chroot-setup-commands='apt remove -y wget'
SBUILD_FLAGS += --chroot-setup-commands='node --version'
SBUILD_FLAGS += --chroot-setup-commands='npm --version'
