# Runtime: Rust
SBUILD_FLAGS += --chroot-setup-commands='apt install -y wget gpg gpg-agent'
SBUILD_FLAGS += --chroot-setup-commands='wget -q -O /tmp/package.tar.xz $(BINARY_URL)'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && echo "$(BINARY_GPG_ASC)" >> package.tar.xz.asc'
SBUILD_FLAGS += --chroot-setup-commands='wget -qO- https://keybase.io/rust/pgp_keys.asc | gpg --import'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && gpg --verify package.tar.xz.asc package.tar.xz'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && tar xJf package.tar.xz -C . --strip-components=1 && rm -f package.tar.xz package.tar.xz.asc'
SBUILD_FLAGS += --chroot-setup-commands='cd /tmp && /bin/bash install.sh --components=rustc,cargo,rust-std-x86_64-unknown-linux-gnu'
SBUILD_FLAGS += --chroot-setup-commands='rm -rf /tmp/rustc /tmp/cargo /tmp/rust-std-x86_64-unknown-linux-gnu /tmp/install.sh'
SBUILD_FLAGS += --chroot-setup-commands='apt remove -y wget gpg gpg-agent'
