use config::PkgConfig;

use crate::recipe::Command;
use crate::variables::VariableResolver;

/// Emits a Makefile from parsed recipe commands and config.
pub struct MakefileEmitter<'a> {
    config: &'a PkgConfig,
    #[allow(dead_code)]
    vars: &'a VariableResolver,
    pipeline_cmds: &'a [Command],
    runtime_cmds: &'a [Command],
}

impl<'a> MakefileEmitter<'a> {
    pub fn new(
        config: &'a PkgConfig,
        vars: &'a VariableResolver,
        pipeline_cmds: &'a [Command],
        runtime_cmds: &'a [Command],
    ) -> Self {
        Self {
            config,
            vars,
            pipeline_cmds,
            runtime_cmds,
        }
    }

    pub fn emit(&self) -> String {
        let mut out = String::new();

        self.emit_header(&mut out);
        self.emit_variables(&mut out);
        self.emit_phony(&mut out);
        self.emit_targets(&mut out);

        out
    }

    fn emit_header(&self, out: &mut String) {
        out.push_str("# Auto-generated by pkg-builder from pkg-builder.toml\n");
        out.push_str("# Do not edit manually — regenerate with: pkg-builder generate\n\n");
    }

    fn emit_variables(&self, out: &mut String) {
        out.push_str("# === Variables ===\n");

        let pkg = &self.config.package;
        let env = &self.config.build_env;

        emit_var(out, "PACKAGE_NAME", &pkg.name);
        emit_var(out, "VERSION", &pkg.version);
        emit_var(out, "REVISION", &pkg.revision);
        emit_var(out, "SPEC_FILE", &pkg.spec_file.display().to_string());
        emit_var(out, "DISTRIBUTION", env.distribution.as_short());
        emit_var(out, "ARCH", &env.arch.to_string());
        emit_var(
            out,
            "BUILD_DIR",
            &env.workdir.display().to_string(),
        );
        emit_var(
            out,
            "CACHE_DIR",
            &env.sbuild_cache_dir.display().to_string(),
        );

        // Source-specific variables
        match &self.config.source {
            config::source::SourceKind::Tarball { url, hash, .. } => {
                emit_var(out, "SOURCE_URL", url);
                if let Some(h) = hash {
                    let algo = if h.len() == 128 { "sha512" } else { "sha256" };
                    emit_var(out, "SOURCE_HASH_ALGO", algo);
                    emit_var(out, "SOURCE_HASH", h);
                }
            }
            config::source::SourceKind::Git { url, tag, .. } => {
                emit_var(out, "GIT_URL", url);
                emit_var(out, "GIT_TAG", tag);
            }
            config::source::SourceKind::Virtual => {}
        }

        // Snapshot
        if let Some(ref date) = env.snapshot_date {
            emit_var(out, "SNAPSHOT_DATE", date);
        }
        if let Some(ref date) = env.snapshot_security_date {
            emit_var(out, "SNAPSHOT_SECURITY_DATE", date);
        }

        // Repo URL
        emit_var(out, "REPO_URL", &env.repo_url());

        // Runtime-specific variables
        self.emit_runtime_variables(out);

        // Derived paths
        out.push_str("ARTIFACTS_DIR = $(BUILD_DIR)/$(PACKAGE_NAME)-$(VERSION)-$(REVISION)\n");
        out.push_str("BUILD_FILES_DIR = $(ARTIFACTS_DIR)/$(PACKAGE_NAME)-$(VERSION)\n");
        out.push_str("TARBALL_PATH = $(ARTIFACTS_DIR)/$(PACKAGE_NAME)_$(VERSION).orig.tar.gz\n");

        // Cache file
        if env.snapshot_date.is_some() {
            out.push_str("CACHE_FILE = $(CACHE_DIR)/$(DISTRIBUTION)-$(ARCH)-$(SNAPSHOT_DATE).tar.gz\n");
        } else {
            out.push_str("CACHE_FILE = $(CACHE_DIR)/$(DISTRIBUTION)-$(ARCH).tar.gz\n");
        }

        out.push('\n');
    }

    fn emit_runtime_variables(&self, out: &mut String) {
        let runtime = match &self.config.runtime {
            Some(rt) => rt,
            None => return,
        };

        // Emit runtime vars as Makefile variables
        // Handle common patterns: binary_url, binary_checksum, etc.
        for (key, value) in &runtime.vars {
            match value {
                toml::Value::String(s) => {
                    let var_name = key.to_uppercase().replace('-', "_");
                    emit_var(out, &var_name, s);
                }
                toml::Value::Array(arr) if key == "packages" => {
                    // Emit indexed package variables
                    for (i, item) in arr.iter().enumerate() {
                        if let toml::Value::Table(table) = item {
                            let n = i + 1;
                            if let Some(toml::Value::String(s)) = table.get("name") {
                                emit_var(out, &format!("PKG{}_NAME", n), s);
                            }
                            if let Some(toml::Value::String(s)) = table.get("url") {
                                emit_var(out, &format!("PKG{}_URL", n), s);
                            }
                            if let Some(toml::Value::String(s)) = table.get("hash") {
                                emit_var(out, &format!("PKG{}_HASH", n), s);
                            }
                        }
                    }
                }
                _ => {}
            }
        }
    }

    fn emit_phony(&self, out: &mut String) {
        out.push_str(
            ".PHONY: all env build source extract debian patch sbuild \
             test test-lintian test-piuparts test-autopkgtest clean\n\n",
        );
    }

    fn emit_targets(&self, out: &mut String) {
        // Determine which test targets to include
        let testing = &self.config.build_env.testing;
        let mut test_deps = Vec::new();
        if testing.run_lintian {
            test_deps.push("test-lintian");
        }
        if testing.run_piuparts {
            test_deps.push("test-piuparts");
        }
        if testing.run_autopkgtest {
            test_deps.push("test-autopkgtest");
        }

        // all target
        if test_deps.is_empty() {
            out.push_str("all: build\n\n");
        } else {
            out.push_str(&format!("all: build {}\n\n", test_deps.join(" ")));
        }

        // Process pipeline commands to generate targets
        self.emit_pipeline_targets(out);

        // Test targets
        self.emit_test_targets(out, &test_deps);

        // Clean target
        out.push_str("# === Clean ===\n");
        out.push_str("clean:\n");
        out.push_str("\trm -rf $(ARTIFACTS_DIR)\n");
    }

    fn emit_pipeline_targets(&self, out: &mut String) {
        // Walk pipeline commands and emit Make targets
        let mut current_phase = "source";
        let mut chroot_commands: Vec<String> = Vec::new();
        let mut has_source = false;

        // First pass: collect chroot commands from runtime
        for cmd in self.runtime_cmds {
            let chroot_cmd = runtime_cmd_to_chroot(cmd);
            if let Some(c) = chroot_cmd {
                chroot_commands.push(c);
            }
        }

        // Process pipeline commands
        for cmd in self.pipeline_cmds {
            match cmd {
                Command::Download { url, dest } => {
                    if !has_source {
                        out.push_str("# === Source ===\n");
                        out.push_str("source:\n");
                        has_source = true;
                    }
                    out.push_str(&format!("\tmkdir -p $(ARTIFACTS_DIR)\n"));
                    out.push_str(&format!(
                        "\twget -q -O {} {}\n",
                        dest.replace("$(build_dir)", "$(ARTIFACTS_DIR)")
                            .replace("{{build_dir}}", "$(ARTIFACTS_DIR)"),
                        url,
                    ));
                    current_phase = "source";
                }
                Command::Verify { algo, hash, file } => {
                    let file = file
                        .replace("$(build_dir)", "$(ARTIFACTS_DIR)")
                        .replace("{{build_dir}}", "$(ARTIFACTS_DIR)");
                    out.push_str(&format!(
                        "\techo \"{}  {}\" | {}sum -c\n",
                        hash, file, algo
                    ));
                }
                Command::Extract { file, dest, strip } => {
                    let file = file
                        .replace("$(build_dir)", "$(ARTIFACTS_DIR)")
                        .replace("{{build_dir}}", "$(ARTIFACTS_DIR)");
                    let dest = dest
                        .replace("$(build_dir)", "$(ARTIFACTS_DIR)")
                        .replace("{{build_dir}}", "$(ARTIFACTS_DIR)");

                    if current_phase == "source" {
                        out.push_str("\n");
                        out.push_str("extract: source\n");
                        current_phase = "extract";
                    }
                    out.push_str(&format!("\tmkdir -p {}\n", dest));
                    match strip {
                        Some(n) => {
                            out.push_str(&format!(
                                "\ttar -C {} -xf {} --strip-components={}\n",
                                dest, file, n
                            ));
                        }
                        None => {
                            out.push_str(&format!("\ttar -C {} -xf {}\n", dest, file));
                        }
                    }
                }
                Command::Debcrafter { spec } => {
                    out.push_str("\n# === Debian packaging ===\n");
                    out.push_str("debian: extract\n");
                    out.push_str(&format!("\tdebcrafter {} $(ARTIFACTS_DIR)\n", spec));
                    current_phase = "debian";
                }
                Command::Patch => {
                    out.push_str("\npatch: debian\n");
                    out.push_str("\techo \"3.0 (quilt)\" > $(BUILD_FILES_DIR)/debian/source/format\n");
                    out.push_str("\tmkdir -p $(BUILD_FILES_DIR)/.pc && echo 2 > $(BUILD_FILES_DIR)/.pc/version\n");
                    out.push_str("\tchmod +x $(BUILD_FILES_DIR)/debian/rules\n");
                    current_phase = "patch";
                }
                Command::Include { name: _ } => {
                    // Runtime commands are already collected; they get injected into sbuild
                }
                Command::Sbuild => {
                    self.emit_sbuild_target(out, &chroot_commands);
                    current_phase = "sbuild";
                }
                Command::SnapshotWorkaround => {
                    chroot_commands.insert(
                        0,
                        r#"echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99snapshot"#
                            .to_string(),
                    );
                }
                Command::SnapshotSecurity { url, codename } => {
                    chroot_commands.push(format!(
                        "echo 'deb {} {}-security main' > /etc/apt/sources.list.d/security-snapshot.list",
                        url, codename
                    ));
                    chroot_commands.push("apt-get update".to_string());
                }
                Command::NobleRepos => {
                    // Insert Noble repo commands before runtime commands
                    let noble_cmds = vec![
                        "apt install -y software-properties-common".to_string(),
                        "add-apt-repository universe".to_string(),
                        "add-apt-repository restricted".to_string(),
                        "add-apt-repository multiverse".to_string(),
                        "apt update".to_string(),
                    ];
                    for (i, cmd) in noble_cmds.into_iter().enumerate() {
                        chroot_commands.insert(i, cmd);
                    }
                }
                Command::GitClone { url, tag } => {
                    if !has_source {
                        out.push_str("# === Source ===\n");
                        out.push_str("source:\n");
                        has_source = true;
                    }
                    out.push_str("\tmkdir -p $(ARTIFACTS_DIR)\n");
                    out.push_str(&format!(
                        "\tgit clone --branch {} {} $(BUILD_FILES_DIR)\n",
                        tag, url
                    ));
                    out.push_str(&format!(
                        "\tcd $(BUILD_FILES_DIR) && git archive --format=tar.gz --prefix=$(PACKAGE_NAME)-$(VERSION)/ HEAD > $(TARBALL_PATH)\n"
                    ));
                    current_phase = "source";
                }
                Command::CreateEmptyTar => {
                    if !has_source {
                        out.push_str("# === Source ===\n");
                        out.push_str("source:\n");
                        has_source = true;
                    }
                    out.push_str("\tmkdir -p $(ARTIFACTS_DIR)\n");
                    out.push_str("\tmkdir -p $(BUILD_FILES_DIR)\n");
                    out.push_str("\ttar -czf $(TARBALL_PATH) -C $(ARTIFACTS_DIR) $(PACKAGE_NAME)-$(VERSION)\n");
                    current_phase = "source";
                }
                // These are handled in runtime, not pipeline
                _ => {}
            }
        }

        // Emit env target
        out.push_str("\n# === Environment ===\n");
        out.push_str("env:\n");

        let uses_snapshot = self.config.build_env.uses_snapshot();
        if uses_snapshot {
            out.push_str("\tsbuild-createchroot --chroot-mode=unshare \\\n");
            out.push_str("\t  --make-sbuild-tarball $(CACHE_FILE) \\\n");
            out.push_str("\t  --debootstrapopts=--no-check-gpg \\\n");
            out.push_str(&format!(
                "\t  $(DISTRIBUTION) /tmp/sbuild-createchroot $(REPO_URL)\n"
            ));
        } else {
            out.push_str("\tsbuild-createchroot --chroot-mode=unshare \\\n");
            out.push_str("\t  --make-sbuild-tarball $(CACHE_FILE) \\\n");
            out.push_str(&format!(
                "\t  $(DISTRIBUTION) /tmp/sbuild-createchroot $(REPO_URL)\n"
            ));
        }

        // build alias
        out.push_str("\nbuild: sbuild\n\n");
    }

    fn emit_sbuild_target(&self, out: &mut String, chroot_commands: &[String]) {
        out.push_str("\n# === Build ===\n");
        out.push_str("sbuild: patch\n");
        out.push_str("\tsbuild \\\n");
        out.push_str("\t  -d $(DISTRIBUTION) \\\n");
        out.push_str("\t  -A -s --source-only-changes \\\n");
        out.push_str("\t  -c $(CACHE_FILE) \\\n");
        out.push_str("\t  -v --chroot-mode=unshare \\\n");

        for cmd in chroot_commands {
            // Escape single quotes in commands
            let escaped = cmd.replace('\'', "'\\''");
            out.push_str(&format!("\t  --chroot-setup-commands='{}' \\\n", escaped));
        }

        // Standard sbuild flags
        out.push_str("\t  --no-run-piuparts \\\n");
        out.push_str("\t  --no-apt-upgrade \\\n");
        out.push_str("\t  --no-apt-distupgrade \\\n");

        if self.config.build_env.testing.run_lintian {
            out.push_str("\t  --run-lintian \\\n");
            out.push_str("\t  --lintian-opt=-i --lintian-opt=--I \\\n");
            out.push_str("\t  --lintian-opt=--suppress-tags --lintian-opt=bad-distribution-in-changes-file \\\n");
            out.push_str("\t  --lintian-opt=--suppress-tags --lintian-opt=debug-file-with-no-debug-symbols \\\n");
            out.push_str("\t  --lintian-opt=--tag-display-limit=0 \\\n");
            out.push_str("\t  --lintian-opts=--fail-on=error --lintian-opts=--fail-on=warning \\\n");
        } else {
            out.push_str("\t  --no-run-lintian \\\n");
        }

        out.push_str("\t  --no-run-autopkgtest \\\n");
        out.push_str("\t  $(BUILD_FILES_DIR)\n");
    }

    fn emit_test_targets(&self, out: &mut String, test_deps: &[&str]) {
        if test_deps.is_empty() {
            return;
        }

        out.push_str("# === Test ===\n");

        if self.config.build_env.testing.run_lintian {
            out.push_str("test-lintian: build\n");
            out.push_str("\tlintian $(ARTIFACTS_DIR)/*.changes\n\n");
        }

        if self.config.build_env.testing.run_piuparts {
            out.push_str("test-piuparts: build\n");
            out.push_str(
                "\tsudo piuparts -d $(DISTRIBUTION) $(ARTIFACTS_DIR)/*.deb\n\n",
            );
        }

        if self.config.build_env.testing.run_autopkgtest {
            out.push_str("test-autopkgtest: build\n");
            out.push_str(
                "\tsudo autopkgtest $(ARTIFACTS_DIR)/*.changes -- qemu $(CACHE_DIR)/autopkgtest-$(DISTRIBUTION)-$(ARCH).img\n\n",
            );
        }

        out.push_str(&format!("test: {}\n\n", test_deps.join(" ")));
    }
}

/// Convert a runtime recipe command to a chroot-setup-command string.
fn runtime_cmd_to_chroot(cmd: &Command) -> Option<String> {
    match cmd {
        Command::AptInstall { packages } => {
            Some(format!("apt install -y {}", packages.join(" ")))
        }
        Command::AptRemove { packages } => {
            Some(format!("apt remove -y {}", packages.join(" ")))
        }
        Command::AptUpdate => Some("apt-get update -y".to_string()),
        Command::Download { url, dest } => {
            Some(format!("wget -q -O {} {}", dest, url))
        }
        Command::Verify { algo, hash, file } => {
            Some(format!(
                "echo '{} {}' | {}sum -c",
                hash, file, algo
            ))
        }
        Command::Extract { file, dest, strip } => match strip {
            Some(n) => Some(format!(
                "tar -C {} -xf {} --strip-components={}",
                dest, file, n
            )),
            None => Some(format!("tar -C {} -xf {}", dest, file)),
        },
        Command::Symlink { src, target } => {
            Some(format!("ln -s {} {}", src, target))
        }
        Command::DpkgInstall { file } => {
            Some(format!("dpkg -i {}", file))
        }
        Command::Run { cmd } => Some(cmd.clone()),
        Command::VerifyGpg { file, sig } => {
            Some(format!("gpg --verify {} {}", sig, file))
        }
        _ => None,
    }
}

fn emit_var(out: &mut String, name: &str, value: &str) {
    out.push_str(&format!("{} = {}\n", name, value));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_runtime_cmd_to_chroot_apt_install() {
        let cmd = Command::AptInstall {
            packages: vec!["wget".into(), "gpg".into()],
        };
        assert_eq!(
            runtime_cmd_to_chroot(&cmd),
            Some("apt install -y wget gpg".to_string())
        );
    }

    #[test]
    fn test_runtime_cmd_to_chroot_download() {
        let cmd = Command::Download {
            url: "https://example.com/file".into(),
            dest: "/tmp/file".into(),
        };
        assert_eq!(
            runtime_cmd_to_chroot(&cmd),
            Some("wget -q -O /tmp/file https://example.com/file".to_string())
        );
    }

    #[test]
    fn test_runtime_cmd_to_chroot_run() {
        let cmd = Command::Run {
            cmd: "go version".into(),
        };
        assert_eq!(
            runtime_cmd_to_chroot(&cmd),
            Some("go version".to_string())
        );
    }

    #[test]
    fn test_runtime_cmd_to_chroot_non_runtime() {
        assert_eq!(runtime_cmd_to_chroot(&Command::Sbuild), None);
        assert_eq!(runtime_cmd_to_chroot(&Command::Patch), None);
    }
}
