use std::path::Path;

use config::PkgConfig;

use crate::recipe::Command;
use crate::variables::VariableResolver;

/// Emits a Makefile from parsed recipe commands and config.
pub struct MakefileEmitter<'a> {
    config: &'a PkgConfig,
    #[allow(dead_code)]
    vars: &'a VariableResolver,
    pipeline_cmds: &'a [Command],
    runtime_cmds: &'a [Command],
}

impl<'a> MakefileEmitter<'a> {
    pub fn new(
        config: &'a PkgConfig,
        vars: &'a VariableResolver,
        pipeline_cmds: &'a [Command],
        runtime_cmds: &'a [Command],
    ) -> Self {
        Self {
            config,
            vars,
            pipeline_cmds,
            runtime_cmds,
        }
    }

    pub fn emit(&self) -> String {
        let mut out = String::new();

        self.emit_header(&mut out);
        self.emit_variables(&mut out);
        self.emit_phony(&mut out);
        self.emit_targets(&mut out);

        out
    }

    fn emit_header(&self, out: &mut String) {
        out.push_str("# Auto-generated by pkg-builder from pkg-builder.toml\n");
        out.push_str("# Do not edit manually — regenerate with: pkg-builder generate\n\n");
        out.push_str("SHELL := /bin/bash\n");
        out.push_str("export PATH := $(HOME)/.cargo/bin:$(PATH)\n\n");
    }

    fn emit_variables(&self, out: &mut String) {
        out.push_str("# === Variables ===\n");

        let pkg = &self.config.package;
        let env = &self.config.build_env;
        let root = &self.config.config_root;

        // Paths
        out.push_str("ROOT := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))\n");
        emit_var(
            out,
            "WORK_DIR",
            &portabilize_path(&env.workdir.display().to_string(), root),
        );
        emit_var(
            out,
            "CHROOT_DIR",
            &portabilize_path(&env.chroot_dir.display().to_string(), root),
        );
        out.push('\n');

        // Package
        emit_var(out, "PKG_NAME", &pkg.name);
        emit_var(out, "PKG_VERSION", &pkg.version);
        emit_var(out, "PKG_REVISION", &pkg.revision);
        emit_var(
            out,
            "PKG_SPEC",
            &portabilize_path(&pkg.spec.display().to_string(), root),
        );
        out.push('\n');

        // Build environment
        emit_var(out, "DISTRIBUTION", env.distribution.as_short());
        emit_var(out, "ARCH", &env.arch.to_string());
        emit_var(out, "REPO_URL", &env.repo_url());
        if let Some(ref date) = env.snapshot_date {
            emit_var(out, "SNAPSHOT_DATE", date);
        }
        if let Some(ref date) = env.snapshot_security_date {
            emit_var(out, "SNAPSHOT_SECURITY_DATE", date);
        }
        out.push('\n');

        // Source
        match &self.config.source {
            config::source::SourceKind::Tarball { url, hash, .. } => {
                emit_var(out, "SRC_URL", &portabilize_path(url, root));
                if let Some(h) = hash {
                    let algo = if h.len() == 128 { "sha512" } else { "sha256" };
                    emit_var(out, "SRC_HASH_ALGO", algo);
                    emit_var(out, "SRC_HASH", h);
                }
                out.push('\n');
            }
            config::source::SourceKind::Git { url, tag, .. } => {
                emit_var(out, "GIT_URL", url);
                emit_var(out, "GIT_TAG", tag);
                out.push('\n');
            }
            config::source::SourceKind::Virtual => {}
        }

        // Tools
        emit_var(out, "DEBCRAFTER_REV", &env.tool_versions.debcrafter);
        out.push_str("DEBCRAFTER = debcrafter-$(DEBCRAFTER_REV)\n");
        out.push('\n');

        // Runtime-specific variables
        self.emit_runtime_variables(out);

        // Derived paths
        out.push_str("OUT_DIR = $(WORK_DIR)/$(PKG_NAME)-$(PKG_VERSION)-$(PKG_REVISION)\n");
        out.push_str("SRC_DIR = $(OUT_DIR)/$(PKG_NAME)-$(PKG_VERSION)\n");
        out.push_str("SRC_TARBALL = $(OUT_DIR)/$(PKG_NAME)_$(PKG_VERSION).orig.tar.gz\n");
        // Aliases used in pipeline recipes
        out.push_str("TARBALL_PATH = $(SRC_TARBALL)\n");
        out.push_str("BUILD_FILES_DIR = $(SRC_DIR)\n");
        if env.snapshot_date.is_some() {
            out.push_str("CHROOT_TARBALL = $(CHROOT_DIR)/$(DISTRIBUTION)-$(ARCH)-$(SNAPSHOT_DATE).tar.gz\n");
        } else {
            out.push_str("CHROOT_TARBALL = $(CHROOT_DIR)/$(DISTRIBUTION)-$(ARCH).tar.gz\n");
        }

        out.push('\n');
    }

    fn emit_runtime_variables(&self, out: &mut String) {
        let runtime = match &self.config.runtime {
            Some(rt) => rt,
            None => return,
        };

        // Emit runtime vars as Makefile variables
        // Handle common patterns: binary_url, binary_checksum, etc.
        for (key, value) in &runtime.vars {
            match value {
                toml::Value::String(s) => {
                    let var_name = key.to_uppercase().replace('-', "_");
                    emit_var(out, &var_name, s);
                }
                toml::Value::Array(arr) if key == "packages" => {
                    // Emit indexed package variables
                    for (i, item) in arr.iter().enumerate() {
                        if let toml::Value::Table(table) = item {
                            let n = i + 1;
                            if let Some(toml::Value::String(s)) = table.get("name") {
                                emit_var(out, &format!("PKG{}_NAME", n), s);
                            }
                            if let Some(toml::Value::String(s)) = table.get("url") {
                                emit_var(out, &format!("PKG{}_URL", n), s);
                            }
                            if let Some(toml::Value::String(s)) = table.get("hash") {
                                emit_var(out, &format!("PKG{}_HASH", n), s);
                            }
                        }
                    }
                }
                _ => {}
            }
        }
    }

    fn emit_phony(&self, out: &mut String) {
        out.push_str(
            ".PHONY: all \\\n\
             \tpreflight \\\n\
             \tenv \\\n\
             \tbuild \\\n\
             \tsource \\\n\
             \textract \\\n\
             \tdebian \\\n\
             \tpatch \\\n\
             \tsbuild \\\n\
             \ttest \\\n\
             \ttest-lintian \\\n\
             \ttest-piuparts \\\n\
             \ttest-autopkgtest \\\n\
             \tclean\n\n",
        );
    }

    fn emit_targets(&self, out: &mut String) {
        // Determine which test targets to include
        let testing = &self.config.build_env.testing;
        let mut test_deps = Vec::new();
        if testing.run_lintian {
            test_deps.push("test-lintian");
        }
        if testing.run_piuparts {
            test_deps.push("test-piuparts");
        }
        if testing.run_autopkgtest {
            test_deps.push("test-autopkgtest");
        }

        // all target
        if test_deps.is_empty() {
            out.push_str("all: build\n\n");
        } else {
            out.push_str(&format!("all: build {}\n\n", test_deps.join(" ")));
        }

        // Preflight check target
        self.emit_preflight_target(out);

        // Process pipeline commands to generate targets
        self.emit_pipeline_targets(out);

        // Test targets
        self.emit_test_targets(out, &test_deps);

        // Clean target
        out.push_str("# === Clean ===\n");
        out.push_str("clean:\n");
        out.push_str("\trm -rf $(OUT_DIR)\n");
    }

    /// Collect the list of required host tools from REQUIRE commands in recipes.
    fn required_tools(&self) -> Vec<String> {
        let mut tools = Vec::new();

        for cmd in self.pipeline_cmds.iter().chain(self.runtime_cmds.iter()) {
            if let Command::Require { tools: req } = cmd {
                for tool in req {
                    if !tools.contains(tool) {
                        tools.push(tool.clone());
                    }
                }
            }
        }

        tools
    }

    /// Collect INSTALL commands from recipes (tool name -> install command).
    fn install_commands(&self) -> Vec<(String, String)> {
        let mut installs = Vec::new();

        for cmd in self.pipeline_cmds.iter().chain(self.runtime_cmds.iter()) {
            if let Command::Install { tool, cmd } = cmd {
                if !installs.iter().any(|(t, _): &(String, String)| t == tool) {
                    installs.push((tool.clone(), cmd.clone()));
                }
            }
        }

        installs
    }

    fn emit_preflight_target(&self, out: &mut String) {
        let tools = self.required_tools();
        let installs = self.install_commands();

        if tools.is_empty() && installs.is_empty() {
            return;
        }

        out.push_str("# === Preflight check ===\n");
        out.push_str("preflight:\n");

        // Auto-install tools that have INSTALL commands
        for (tool, cmd) in &installs {
            let (check_name, install_cmd) = if tool == "debcrafter" {
                (
                    "$(DEBCRAFTER)".to_string(),
                    format!("{} && cp $(HOME)/.cargo/bin/debcrafter $(HOME)/.cargo/bin/$(DEBCRAFTER)", cmd),
                )
            } else {
                (tool.clone(), cmd.clone())
            };
            out.push_str(&format!(
                "\t@if ! command -v {} >/dev/null 2>&1; then \\\n\t  echo \"Installing {}...\"; \\\n\t  {}; \\\n\tfi\n",
                check_name, check_name, install_cmd
            ));
        }

        // Check remaining required tools
        if !tools.is_empty() {
            out.push_str("\t@missing=\"\"; \\\n");
            for tool in &tools {
                let check_name = if tool == "debcrafter" { "$(DEBCRAFTER)" } else { tool };
                out.push_str(&format!(
                    "\tif ! command -v {} >/dev/null 2>&1; then missing=\"$$missing {}\"; fi; \\\n",
                    check_name, check_name
                ));
            }
            out.push_str("\tif [ -n \"$$missing\" ]; then \\\n");
            out.push_str("\t  echo \"Error: missing required tool(s):$$missing\"; \\\n");
            out.push_str("\t  exit 1; \\\n");
            out.push_str("\tfi; \\\n");
            out.push_str("\techo \"All required tools found.\"\n");
        }

        out.push('\n');
    }

    fn emit_pipeline_targets(&self, out: &mut String) {
        // Walk pipeline commands and emit Make targets
        let mut current_phase = "source";
        let mut chroot_commands: Vec<String> = Vec::new();
        let mut has_source = false;

        // First pass: collect chroot commands from runtime
        for cmd in self.runtime_cmds {
            let chroot_cmd = runtime_cmd_to_chroot(cmd);
            if let Some(c) = chroot_cmd {
                chroot_commands.push(c);
            }
        }

        // Process pipeline commands
        for cmd in self.pipeline_cmds {
            match cmd {
                Command::Download { url, dest } => {
                    if !has_source {
                        out.push_str("# === Source ===\n");
                        out.push_str("source: preflight\n");
                        has_source = true;
                    }
                    let dest = dest
                        .replace("$(build_dir)", "$(OUT_DIR)")
                        .replace("{{build_dir}}", "$(OUT_DIR)");
                    out.push_str("\tmkdir -p $(OUT_DIR)\n");
                    if url.starts_with("http://") || url.starts_with("https://") {
                        out.push_str(&format!("\twget -q -O {} {}\n", dest, url));
                    } else {
                        out.push_str(&format!("\tcp $(SRC_URL) {}\n", dest));
                    }
                    current_phase = "source";
                }
                Command::Verify { algo: _, hash: _, file } => {
                    let file = file
                        .replace("$(build_dir)", "$(OUT_DIR)")
                        .replace("{{build_dir}}", "$(OUT_DIR)");
                    out.push_str(&format!(
                        "\techo \"$(SRC_HASH)  {}\" | $(SRC_HASH_ALGO)sum -c\n",
                        file
                    ));
                }
                Command::Extract { file, dest, strip } => {
                    let file = file
                        .replace("$(build_dir)", "$(OUT_DIR)")
                        .replace("{{build_dir}}", "$(OUT_DIR)");
                    let dest = dest
                        .replace("$(build_dir)", "$(OUT_DIR)")
                        .replace("{{build_dir}}", "$(OUT_DIR)");

                    if current_phase == "source" {
                        out.push_str("\n");
                        out.push_str("extract: source\n");
                        current_phase = "extract";
                    }
                    out.push_str(&format!("\tmkdir -p {}\n", dest));
                    match strip {
                        Some(n) => {
                            out.push_str(&format!(
                                "\ttar -C {} -xf {} --strip-components={}\n",
                                dest, file, n
                            ));
                        }
                        None => {
                            out.push_str(&format!("\ttar -C {} -xf {}\n", dest, file));
                        }
                    }
                }
                Command::Debcrafter { spec: _ } => {
                    out.push_str("\n# === Debian packaging ===\n");
                    out.push_str("debian: extract\n");
                    out.push_str("\t$(DEBCRAFTER) $(PKG_SPEC) $(OUT_DIR)\n");
                    current_phase = "debian";
                }
                Command::Patch => {
                    out.push_str("\npatch: debian\n");
                    out.push_str("\tmkdir -p $(SRC_DIR)/debian/source\n");
                    out.push_str("\techo \"3.0 (quilt)\" > $(SRC_DIR)/debian/source/format\n");
                    out.push_str("\tmkdir -p $(SRC_DIR)/.pc && echo 2 > $(SRC_DIR)/.pc/version\n");
                    out.push_str("\tif [ -d $(ROOT)/src ]; then cp -r $(ROOT)/src/. $(SRC_DIR)/; fi\n");
                    out.push_str("\tchmod +x $(SRC_DIR)/debian/rules\n");
                    current_phase = "patch";
                }
                Command::Include { name: _ } => {
                    // Runtime commands are already collected; they get injected into sbuild
                }
                Command::Sbuild => {
                    self.emit_sbuild_target(out, &chroot_commands);
                    current_phase = "sbuild";
                }
                Command::SnapshotWorkaround => {
                    chroot_commands.insert(
                        0,
                        r#"echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99snapshot"#
                            .to_string(),
                    );
                }
                Command::SnapshotSecurity { url, codename } => {
                    chroot_commands.push(format!(
                        "echo 'deb {} {}-security main' > /etc/apt/sources.list.d/security-snapshot.list",
                        url, codename
                    ));
                    chroot_commands.push("apt-get update".to_string());
                }
                Command::NobleRepos => {
                    // Insert Noble repo commands before runtime commands
                    let noble_cmds = vec![
                        "apt install -y software-properties-common".to_string(),
                        "add-apt-repository universe".to_string(),
                        "add-apt-repository restricted".to_string(),
                        "add-apt-repository multiverse".to_string(),
                        "apt update".to_string(),
                    ];
                    for (i, cmd) in noble_cmds.into_iter().enumerate() {
                        chroot_commands.insert(i, cmd);
                    }
                }
                Command::GitClone { url, tag } => {
                    if !has_source {
                        out.push_str("# === Source ===\n");
                        out.push_str("source: preflight\n");
                        has_source = true;
                    }
                    out.push_str("\tmkdir -p $(OUT_DIR)\n");
                    out.push_str(&format!(
                        "\tgit clone --branch {} {} $(SRC_DIR)\n",
                        tag, url
                    ));
                    out.push_str(&format!(
                        "\tcd $(SRC_DIR) && git archive --format=tar.gz --prefix=$(PKG_NAME)-$(PKG_VERSION)/ HEAD > $(SRC_TARBALL)\n"
                    ));
                    current_phase = "source";
                }
                Command::CreateEmptyTar => {
                    if !has_source {
                        out.push_str("# === Source ===\n");
                        out.push_str("source: preflight\n");
                        has_source = true;
                    }
                    out.push_str("\tmkdir -p $(OUT_DIR)\n");
                    out.push_str("\tmkdir -p $(SRC_DIR)\n");
                    out.push_str("\ttar -czf $(SRC_TARBALL) -C $(OUT_DIR) $(PKG_NAME)-$(PKG_VERSION)\n");
                    current_phase = "source";
                }
                // These are handled in runtime, not pipeline
                _ => {}
            }
        }

        // Emit env target
        out.push_str("\n# === Environment ===\n");
        out.push_str("env: preflight\n");

        let uses_snapshot = self.config.build_env.uses_snapshot();
        if uses_snapshot {
            out.push_str("\tsbuild-createchroot --chroot-mode=unshare \\\n");
            out.push_str("\t  --make-sbuild-tarball $(CHROOT_TARBALL) \\\n");
            out.push_str("\t  --debootstrapopts=--no-check-gpg \\\n");
            out.push_str("\t  $(DISTRIBUTION) /tmp/sbuild-createchroot $(REPO_URL)\n");
        } else {
            out.push_str("\tsbuild-createchroot --chroot-mode=unshare \\\n");
            out.push_str("\t  --make-sbuild-tarball $(CHROOT_TARBALL) \\\n");
            out.push_str("\t  $(DISTRIBUTION) /tmp/sbuild-createchroot $(REPO_URL)\n");
        }

        // build alias
        out.push_str("\nbuild: sbuild\n\n");
    }

    fn emit_sbuild_target(&self, out: &mut String, chroot_commands: &[String]) {
        out.push_str("\n# === Build ===\n");
        out.push_str("sbuild: patch\n");
        out.push_str("\tsbuild \\\n");
        out.push_str("\t  -d $(DISTRIBUTION) \\\n");
        out.push_str("\t  -A -s --source-only-changes \\\n");
        out.push_str("\t  -c $(CHROOT_TARBALL) \\\n");
        out.push_str("\t  -v --chroot-mode=unshare \\\n");

        for cmd in chroot_commands {
            // Escape single quotes in commands
            let escaped = cmd.replace('\'', "'\\''");
            out.push_str(&format!("\t  --chroot-setup-commands='{}' \\\n", escaped));
        }

        // Standard sbuild flags
        out.push_str("\t  --no-run-piuparts \\\n");
        out.push_str("\t  --no-apt-upgrade \\\n");
        out.push_str("\t  --no-apt-distupgrade \\\n");

        if self.config.build_env.testing.run_lintian {
            out.push_str("\t  --run-lintian \\\n");
            out.push_str("\t  --lintian-opt=-i --lintian-opt=--I \\\n");
            out.push_str("\t  --lintian-opt=--suppress-tags --lintian-opt=bad-distribution-in-changes-file \\\n");
            out.push_str("\t  --lintian-opt=--suppress-tags --lintian-opt=debug-file-with-no-debug-symbols \\\n");
            out.push_str("\t  --lintian-opt=--tag-display-limit=0 \\\n");
            out.push_str("\t  --lintian-opts=--fail-on=error --lintian-opts=--fail-on=warning \\\n");
        } else {
            out.push_str("\t  --no-run-lintian \\\n");
        }

        out.push_str("\t  --no-run-autopkgtest \\\n");
        out.push_str("\t  --build-dir=$(OUT_DIR) \\\n");
        out.push_str("\t  $(SRC_DIR)\n");
    }

    fn emit_test_targets(&self, out: &mut String, test_deps: &[&str]) {
        if test_deps.is_empty() {
            return;
        }

        out.push_str("# === Test ===\n");

        if self.config.build_env.testing.run_lintian {
            out.push_str("test-lintian: build\n");
            out.push_str("\tlintian $(OUT_DIR)/*.changes\n\n");
        }

        if self.config.build_env.testing.run_piuparts {
            out.push_str("test-piuparts: build\n");
            out.push_str(
                "\tsudo piuparts -d $(DISTRIBUTION) $(OUT_DIR)/*.deb\n\n",
            );
        }

        if self.config.build_env.testing.run_autopkgtest {
            out.push_str("test-autopkgtest: build\n");
            out.push_str(
                "\tsudo autopkgtest $(OUT_DIR)/*.changes -- qemu $(CHROOT_DIR)/autopkgtest-$(DISTRIBUTION)-$(ARCH).img\n\n",
            );
        }

        out.push_str(&format!("test: {}\n\n", test_deps.join(" ")));
    }
}

/// Convert a runtime recipe command to a chroot-setup-command string.
fn runtime_cmd_to_chroot(cmd: &Command) -> Option<String> {
    match cmd {
        Command::AptInstall { packages } => {
            Some(format!("apt install -y {}", packages.join(" ")))
        }
        Command::AptRemove { packages } => {
            Some(format!("apt remove -y {}", packages.join(" ")))
        }
        Command::AptUpdate => Some("apt-get update -y".to_string()),
        Command::Download { url, dest } => {
            Some(format!("wget -q -O {} {}", dest, url))
        }
        Command::Verify { algo, hash, file } => {
            Some(format!(
                "echo '{} {}' | {}sum -c",
                hash, file, algo
            ))
        }
        Command::Extract { file, dest, strip } => match strip {
            Some(n) => Some(format!(
                "tar -C {} -xf {} --strip-components={}",
                dest, file, n
            )),
            None => Some(format!("tar -C {} -xf {}", dest, file)),
        },
        Command::Symlink { src, target } => {
            Some(format!("ln -s {} {}", src, target))
        }
        Command::DpkgInstall { file } => {
            Some(format!("dpkg -i {}", file))
        }
        Command::Run { cmd } => Some(cmd.clone()),
        Command::VerifyGpg { file, sig } => {
            Some(format!("gpg --verify {} {}", sig, file))
        }
        _ => None,
    }
}

fn emit_var(out: &mut String, name: &str, value: &str) {
    out.push_str(&format!("{} = {}\n", name, value));
}

/// Convert an absolute path to a portable Makefile-friendly path.
/// Replaces config_root prefix with $(ROOT) and home dir with $(HOME).
fn portabilize_path(path: &str, config_root: &Path) -> String {
    let config_root_str = config_root.display().to_string();

    // Check config_root first (more specific, likely under home)
    if let Some(rel) = path.strip_prefix(&config_root_str) {
        let rel = rel.strip_prefix('/').unwrap_or(rel);
        if rel.is_empty() {
            return "$(ROOT)".to_string();
        }
        return format!("$(ROOT)/{}", rel);
    }

    // Replace home directory with $(HOME)
    if let Ok(home) = std::env::var("HOME") {
        if let Some(rel) = path.strip_prefix(&home) {
            let rel = rel.strip_prefix('/').unwrap_or(rel);
            return format!("$(HOME)/{}", rel);
        }
    }

    path.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_runtime_cmd_to_chroot_apt_install() {
        let cmd = Command::AptInstall {
            packages: vec!["wget".into(), "gpg".into()],
        };
        assert_eq!(
            runtime_cmd_to_chroot(&cmd),
            Some("apt install -y wget gpg".to_string())
        );
    }

    #[test]
    fn test_runtime_cmd_to_chroot_download() {
        let cmd = Command::Download {
            url: "https://example.com/file".into(),
            dest: "/tmp/file".into(),
        };
        assert_eq!(
            runtime_cmd_to_chroot(&cmd),
            Some("wget -q -O /tmp/file https://example.com/file".to_string())
        );
    }

    #[test]
    fn test_runtime_cmd_to_chroot_run() {
        let cmd = Command::Run {
            cmd: "go version".into(),
        };
        assert_eq!(
            runtime_cmd_to_chroot(&cmd),
            Some("go version".to_string())
        );
    }

    #[test]
    fn test_runtime_cmd_to_chroot_non_runtime() {
        assert_eq!(runtime_cmd_to_chroot(&Command::Sbuild), None);
        assert_eq!(runtime_cmd_to_chroot(&Command::Patch), None);
    }
}
