use crate::ir::{BuildPlan, Condition, Operation, Phase, Preamble, VarDecl, VarValue, AssignKind};

/// Escape a string for safe use inside single-quoted shell arguments.
/// Replaces `'` with `'\''` (end quote, escaped quote, restart quote).
fn shell_escape(s: &str) -> String {
    s.replace('\'', "'\\''")
}

/// Render a BuildPlan as a Makefile string.
pub fn render_makefile(plan: &BuildPlan) -> String {
    let mut out = String::new();

    render_header(&mut out);
    render_variables(&mut out, &plan.preamble);
    render_phony(&mut out);
    render_targets(&mut out, plan);

    out
}

fn render_header(out: &mut String) {
    out.push_str("# Auto-generated by pkg-builder from pkg-builder.toml\n");
    out.push_str("# Do not edit manually — regenerate with: pkg-builder generate\n\n");
    out.push_str("SHELL       := /bin/bash\n");
    out.push_str(".SHELLFLAGS := -eo pipefail -c\n");
    out.push_str(".DELETE_ON_ERROR:\n");
    out.push_str(".NOTPARALLEL:\n");
    out.push_str("export PATH := $(HOME)/.cargo/bin:$(PATH)\n");
    out.push_str("INSTALL_DEPS ?= 0\n\n");
}

fn render_variables(out: &mut String, preamble: &Preamble) {
    out.push_str("# === Variables ===\n");

    for var in &preamble.variables {
        render_var_decl(out, var);
    }
}

fn render_var_decl(out: &mut String, var: &VarDecl) {
    // Raw entries are emitted verbatim
    if let VarValue::Raw(text) = &var.value {
        out.push_str(text);
        return;
    }

    let op = match var.kind {
        AssignKind::Immediate => ":=",
        AssignKind::Deferred => "=",
        AssignKind::Default => "?=",
        AssignKind::Append => "+=",
    };

    match &var.value {
        VarValue::Literal(s) => {
            if s.contains('\n') {
                out.push_str(&format!("define {}\n{}\nendef\n", var.name, s));
            } else {
                out.push_str(&format!("{} {} {}\n", var.name, op, s));
            }
        }
        VarValue::List(items) => {
            out.push_str(&format!("{} {} {}\n", var.name, op, items.join(" ")));
        }
        VarValue::Raw(_) => unreachable!(),
    }
}

fn render_phony(out: &mut String) {
    out.push_str(
        ".PHONY: all \\\n\
         \tpreflight \\\n\
         \tenv \\\n\
         \tenv-clean \\\n\
         \tbuild \\\n\
         \tsource \\\n\
         \textract \\\n\
         \tdebian \\\n\
         \tpatch \\\n\
         \tsbuild \\\n\
         \ttest \\\n\
         \ttest-lintian \\\n\
         \ttest-piuparts \\\n\
         \ttest-autopkgtest \\\n\
         \thelp \\\n\
         \tclean\n\n",
    );
}

fn render_targets(out: &mut String, plan: &BuildPlan) {
    out.push_str("all: build $(TEST_TARGETS)\n\n");

    // Help target
    render_help_target(out);

    // Preflight
    render_preflight_target(out, &plan.preamble);

    // All build phases
    for phase in &plan.phases {
        render_phase(out, phase, plan);
    }
}

fn render_help_target(out: &mut String) {
    out.push_str("# === Help ===\n");
    out.push_str("help:\n");
    out.push_str("\t@echo \"Targets:\"\n");
    out.push_str("\t@echo \"  make env      Create sbuild chroot\"\n");
    out.push_str("\t@echo \"  make build    Build package\"\n");
    out.push_str("\t@echo \"  make test     Run all tests\"\n");
    out.push_str("\t@echo \"  make clean    Remove build artifacts\"\n");
    out.push('\n');
}

fn render_preflight_target(out: &mut String, preamble: &Preamble) {
    let tools = &preamble.required_tools;
    let installs = &preamble.installable_tools;

    if tools.is_empty() && installs.is_empty() {
        return;
    }

    out.push_str("# === Preflight check ===\n");
    out.push_str("preflight:\n");

    for install in installs {
        let check_name = if install.name == "debcrafter" {
            "$(DEBCRAFTER)".to_string()
        } else {
            install.name.clone()
        };
        let install_hint = if install.name == "debcrafter" {
            format!(
                "{} && cp $(HOME)/.cargo/bin/debcrafter $(HOME)/.cargo/bin/$(DEBCRAFTER)",
                install.install_cmd
            )
        } else {
            install.install_cmd.clone()
        };
        out.push_str(&format!(
            "\t@command -v {check} >/dev/null 2>&1 || {{ \\\n\
             \t  if [ \"$(INSTALL_DEPS)\" = \"1\" ]; then \\\n\
             \t    echo 'Installing {check}...'; \\\n\
             \t    {hint}; \\\n\
             \t  else \\\n\
             \t    echo 'Missing {check}. Install with:'; \\\n\
             \t    echo '  {hint}'; \\\n\
             \t    exit 1; \\\n\
             \t  fi; \\\n\
             \t}}\n",
            check = check_name,
            hint = install_hint,
        ));
    }

    if !tools.is_empty() {
        out.push_str("\t@missing=''; \\\n");
        for tool in tools {
            let check_name = if tool == "debcrafter" {
                "$(DEBCRAFTER)"
            } else {
                tool
            };
            out.push_str(&format!(
                "\tcommand -v {check} >/dev/null 2>&1 || missing=\"$$missing {check}\"; \\\n",
                check = check_name,
            ));
        }
        out.push_str(
            "\t[ -z \"$$missing\" ] || { echo \"Error: missing required tool(s):$$missing\"; exit 1; }; \\\n",
        );
        out.push_str("\techo 'All required tools found.'\n");
    }

    out.push('\n');
}

fn render_phase(out: &mut String, phase: &Phase, plan: &BuildPlan) {
    if let Some(ref cond) = phase.condition {
        match cond {
            Condition::Eq(a, b) => out.push_str(&format!("ifeq ({},{})\n", a, b)),
            Condition::Neq(a, b) => out.push_str(&format!("ifneq ({},{})\n", a, b)),
        }
    }

    // Render based on the phase's semantic name/role
    match phase.name.as_str() {
        "directories" => render_directories_phase(out, phase),
        "source" => render_source_phase(out, phase),
        "debian" => render_debian_phase(out, phase),
        "patch" => render_patch_phase(out, phase),
        "sbuild_flags" => render_sbuild_flags(out),
        "build" => render_build_phase(out, phase, &plan.preamble.chroot_setup),
        "phony_aliases" => render_phony_aliases(out),
        "env" => render_env_phase(out, phase),
        "test" => render_test_phase(out),
        "clean" => render_clean_phase(out),
        _ => {}
    }

    if phase.condition.is_some() {
        out.push_str("endif\n");
    }
}

fn render_directories_phase(out: &mut String, phase: &Phase) {
    out.push_str("# === Directories ===\n");
    if let Some(ref output) = phase.output {
        out.push_str(&format!("{}:\n", output));
    }
    out.push_str("\tmkdir -p $@\n\n");
}

fn render_source_phase(out: &mut String, phase: &Phase) {
    out.push_str("# === Source ===\n");

    let output = phase.output.as_deref().unwrap_or("$(SRC_TARBALL)");
    let order_only = if phase.order_only_deps.is_empty() {
        String::new()
    } else {
        format!(" | {}", phase.order_only_deps.join(" "))
    };

    // Collect submodule checkouts
    let submodule_ops: Vec<_> = phase
        .operations
        .iter()
        .filter_map(|op| {
            if let Operation::SubmoduleCheckout { path, commit } = op {
                Some((path.clone(), commit.clone()))
            } else {
                None
            }
        })
        .collect();

    let is_git = phase
        .operations
        .iter()
        .any(|op| matches!(op, Operation::GitClone { .. }));

    for op in &phase.operations {
        match op {
            Operation::Download { url, .. } => {
                if url.starts_with("http://") || url.starts_with("https://") {
                    out.push_str(&format!("{}:{}\n", output, order_only));
                    out.push_str(&format!("\twget -q -O $@ '{}'\n", shell_escape(url)));
                } else {
                    let deps = if phase.deps.is_empty() {
                        String::new()
                    } else {
                        format!(" {}", phase.deps.join(" "))
                    };
                    out.push_str(&format!("{}:{}{}\n", output, deps, order_only));
                    out.push_str("\tcp $< $@\n");
                }
            }
            Operation::Verify { .. } => {
                out.push_str("\techo \"$(SRC_HASH)  $@\" | $(SRC_HASH_ALGO)sum -c\n");
            }
            Operation::GitClone { url, tag } => {
                out.push_str(&format!("{}:{}\n", output, order_only));
                out.push_str(&format!(
                    "\tgit clone --depth=1 --branch '{}' '{}' $(SRC_DIR)\n",
                    shell_escape(tag), shell_escape(url)
                ));
                out.push_str("\tcd $(SRC_DIR) && git submodule update --init --recursive\n");
                // Submodule checkouts
                for (path, commit) in &submodule_ops {
                    out.push_str(&format!(
                        "\tcd $(SRC_DIR)/'{}' && git fetch origin '{}' && git checkout '{}'\n",
                        shell_escape(path), shell_escape(commit), shell_escape(commit)
                    ));
                }
                // Remove .git and create reproducible tarball
                out.push_str("\trm -rf $(SRC_DIR)/.git\n");
                out.push_str("\tfind $(SRC_DIR) -name '.git' -exec rm -rf {} +\n");
                out.push_str("\ttar --sort=name --owner=0 --group=0 --numeric-owner \\\n");
                out.push_str("\t  '--pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime' \\\n");
                out.push_str("\t  -czf $@ -C $(OUT_DIR) $(PKG_NAME)-$(PKG_VERSION)\n");
            }
            Operation::CreateEmptyTar => {
                out.push_str(&format!("{}:{}\n", output, order_only));
                out.push_str("\tmkdir -p $(SRC_DIR)\n");
                out.push_str("\ttar czvf $@ --files-from /dev/null\n");
            }
            Operation::SubmoduleCheckout { .. } => {
                // Already handled inside GitClone rendering
            }
            _ => {}
        }
    }

    // For non-git sources, no extra tarball creation needed
    if !is_git {
        // Already complete
    }
}

fn render_debian_phase(out: &mut String, phase: &Phase) {
    let output = phase.output.as_deref().unwrap_or("$(SRC_DIR)/debian/rules");
    let deps = if phase.deps.is_empty() {
        String::new()
    } else {
        format!(" {}", phase.deps.join(" "))
    };

    out.push_str(&format!("\n# === Debian packaging ===\n{}:{}\n", output, deps));

    for op in &phase.operations {
        match op {
            Operation::Extract { dest, strip, .. } => {
                let dest = dest
                    .replace("$(build_dir)", "$(OUT_DIR)")
                    .replace("{{build_dir}}", "$(OUT_DIR)")
                    .replace("$(BUILD_FILES_DIR)", "$(SRC_DIR)");
                out.push_str(&format!("\tmkdir -p {}\n", dest));
                match strip {
                    Some(n) => out.push_str(&format!(
                        "\ttar -C {} -xf $(SRC_TARBALL) --strip-components={}\n",
                        dest, n
                    )),
                    None => out.push_str(&format!("\ttar -C {} -xf $(SRC_TARBALL)\n", dest)),
                }
            }
            Operation::Debcrafter { .. } => {
                out.push_str("\t$(DEBCRAFTER) $(PKG_SPEC) $(OUT_DIR)\n");
            }
            _ => {}
        }
    }
}

fn render_patch_phase(out: &mut String, phase: &Phase) {
    let output = phase
        .output
        .as_deref()
        .unwrap_or("$(SRC_DIR)/debian/source/format");
    let deps = if phase.deps.is_empty() {
        String::new()
    } else {
        format!(" {}", phase.deps.join(" "))
    };

    out.push_str(&format!("\n{}:{}\n", output, deps));
    out.push_str("\tmkdir -p $(SRC_DIR)/debian/source\n");
    out.push_str("\techo \"3.0 (quilt)\" > $@\n");
    out.push_str("\tmkdir -p $(SRC_DIR)/.pc && echo 2 > $(SRC_DIR)/.pc/version\n");
    out.push_str("\tif [ -d $(ROOT)/src ]; then cp -r $(ROOT)/src/. $(SRC_DIR)/; fi\n");
    out.push_str("\tchmod +x $(SRC_DIR)/debian/rules\n");
    out.push_str("\t@cd $(SRC_DIR) && \\\n");
    out.push_str("\t  if ! grep -q '^Standards-Version:' debian/control; then \\\n");
    out.push_str("\t    awk -v hp='$(PKG_HOMEPAGE)' '\\\n");
    out.push_str("\t      /^Priority:/ && !done { print; print \"Standards-Version: 4.5.1\"; print \"Homepage: \" hp; done=1; next } \\\n");
    out.push_str("\t      { print }' debian/control > debian/control.tmp && \\\n");
    out.push_str("\t    mv debian/control.tmp debian/control; \\\n");
    out.push_str("\t  fi\n");
    out.push_str("\t@cd $(SRC_DIR) && \\\n");
    out.push_str("\t  awk 'BEGIN{blank=0} /^$$/{blank++; if(blank==1) print; next} {blank=0; print}' debian/control > debian/control.tmp && \\\n");
    out.push_str("\t  mv debian/control.tmp debian/control\n");
}

fn render_sbuild_flags(out: &mut String) {
    out.push_str("\n# === Build ===\n");
    out.push_str("SBUILD_FLAGS := \\\n");
    out.push_str("\t  -d $(DISTRIBUTION) \\\n");
    out.push_str("\t  -A -s --source-only-changes \\\n");
    out.push_str("\t  -c $(CHROOT_TARBALL) \\\n");
    out.push_str("\t  -v --chroot-mode=unshare \\\n");
    out.push_str("\t  --no-run-piuparts \\\n");
    out.push_str("\t  --no-apt-upgrade \\\n");
    out.push_str("\t  --no-apt-distupgrade\n");
    out.push_str("ifeq ($(RUN_LINTIAN),true)\n");
    out.push_str("SBUILD_FLAGS += \\\n");
    out.push_str("\t  --run-lintian \\\n");
    out.push_str("\t  --lintian-opt=-i --lintian-opt=--I \\\n");
    out.push_str("\t  --lintian-opt=--suppress-tags --lintian-opt=bad-distribution-in-changes-file \\\n");
    out.push_str("\t  --lintian-opt=--suppress-tags --lintian-opt=debug-file-with-no-debug-symbols \\\n");
    out.push_str("\t  --lintian-opt=--tag-display-limit=0 \\\n");
    out.push_str("\t  --lintian-opts=--fail-on=error --lintian-opts=--fail-on=warning\n");
    out.push_str("else\n");
    out.push_str("SBUILD_FLAGS += --no-run-lintian\n");
    out.push_str("endif\n");
    out.push_str("SBUILD_FLAGS += \\\n");
    out.push_str("\t  --no-run-autopkgtest \\\n");
    out.push_str("\t  --build-dir=$(OUT_DIR)\n");
    out.push('\n');
}

fn render_build_phase(out: &mut String, phase: &Phase, chroot_setup: &[Operation]) {
    let output = phase.output.as_deref().unwrap_or("$(OUT_DIR)/.built");
    let deps = phase.deps.join(" ");

    out.push_str(&format!("{}: {}\n", output, deps));
    out.push_str("\tsbuild $(SBUILD_FLAGS) \\\n");

    // Convert chroot_setup operations to chroot-setup-commands
    let chroot_commands = operations_to_chroot_commands(chroot_setup);
    for cmd in &chroot_commands {
        if cmd.contains('\n') {
            let escaped = cmd
                .replace('\\', "\\\\")
                .replace('\'', "\\'")
                .replace('\n', "\\n");
            out.push_str(&format!("\t  --chroot-setup-commands=$$'{}' \\\n", escaped));
        } else {
            let escaped = cmd.replace('\'', "'\\''");
            out.push_str(&format!("\t  --chroot-setup-commands='{}' \\\n", escaped));
        }
    }

    out.push_str("\t  $(SRC_DIR)\n");
    out.push_str("\ttouch $@\n");
}

fn render_phony_aliases(out: &mut String) {
    out.push_str("\n# === Phony aliases ===\n");
    out.push_str("source: $(SRC_TARBALL)\n");
    out.push_str("extract: source\n");
    out.push_str("debian: $(SRC_DIR)/debian/rules\n");
    out.push_str("patch: $(SRC_DIR)/debian/source/format\n");
    out.push_str("sbuild build: $(OUT_DIR)/.built\n");
}

fn render_env_phase(out: &mut String, phase: &Phase) {
    out.push_str("\n# === Environment ===\n");

    let order_only = if phase.order_only_deps.is_empty() {
        String::new()
    } else {
        format!(" | {}", phase.order_only_deps.join(" "))
    };

    // Check if uses snapshot (marker operation present)
    let uses_snapshot = phase.operations.iter().any(|op| {
        matches!(op, Operation::Run { cmd } if cmd == "__uses_snapshot")
    });

    out.push_str(&format!("$(CHROOT_TARBALL):{}\n", order_only));
    if uses_snapshot {
        // Snapshot archives have expired Release signatures, so GPG verification
        // must be disabled for debootstrap. This is a known security trade-off:
        // we trust snapshot.debian.org over HTTPS instead of GPG signatures.
        out.push_str("\tsbuild-createchroot --chroot-mode=unshare \\\n");
        out.push_str("\t  --make-sbuild-tarball $@ \\\n");
        out.push_str("\t  --debootstrapopts=--no-check-gpg \\\n");
        out.push_str("\t  $(DISTRIBUTION) /tmp/sbuild-createchroot $(REPO_URL)\n");
    } else {
        out.push_str("\tsbuild-createchroot --chroot-mode=unshare \\\n");
        out.push_str("\t  --make-sbuild-tarball $@ \\\n");
        out.push_str("\t  $(DISTRIBUTION) /tmp/sbuild-createchroot $(REPO_URL)\n");
    }
    out.push_str("env: $(CHROOT_TARBALL)\n\n");
    out.push_str("env-clean:\n");
    out.push_str("\trm -f $(CHROOT_TARBALL)\n");
    out.push('\n');
}

fn render_test_phase(out: &mut String) {
    out.push_str("# === Test ===\n");

    out.push_str("test-lintian: build\n");
    out.push_str("\tlintian -i -I --tag-display-limit=0 \\\n");
    out.push_str("\t  --suppress-tags bad-distribution-in-changes-file \\\n");
    out.push_str("\t  --suppress-tags debug-file-with-no-debug-symbols \\\n");
    out.push_str("\t  --fail-on=error --fail-on=warning \\\n");
    out.push_str("\t  $(OUT_DIR)/*.changes\n\n");

    out.push_str("ifeq ($(RUN_PIUPARTS),true)\n");
    out.push_str("test-piuparts: build\n");
    out.push_str("\tsudo piuparts -d $(DISTRIBUTION) $(OUT_DIR)/*.deb\n");
    out.push_str("endif\n\n");

    out.push_str("ifeq ($(RUN_AUTOPKGTEST),true)\n");
    out.push_str("test-autopkgtest: build\n");
    out.push_str(
        "\tsudo autopkgtest $(OUT_DIR)/*.changes -- qemu $(CHROOT_DIR)/autopkgtest-$(DISTRIBUTION)-$(ARCH).img\n",
    );
    out.push_str("endif\n\n");

    out.push_str("test: $(TEST_TARGETS)\n\n");
}

fn render_clean_phase(out: &mut String) {
    out.push_str("# === Clean ===\n");
    out.push_str("clean:\n");
    out.push_str("\trm -rf $(OUT_DIR)\n");
}

/// Convert runtime operations to chroot-setup-command strings.
fn operations_to_chroot_commands(ops: &[Operation]) -> Vec<String> {
    let mut cmds = Vec::new();
    for op in ops {
        if let Some(cmd) = operation_to_chroot(op) {
            cmds.push(cmd);
        }
    }
    cmds
}

/// Convert a single operation to a chroot-setup-command string.
fn operation_to_chroot(op: &Operation) -> Option<String> {
    match op {
        Operation::AptInstall { packages } => Some(format!("apt install -y {}", packages.join(" "))),
        Operation::AptRemove { packages } => Some(format!("apt remove -y {}", packages.join(" "))),
        Operation::AptUpdate => Some("apt-get update -y".to_string()),
        Operation::Download { url, dest } => Some(format!("wget -q -O {} {}", dest, url)),
        Operation::Verify { algo, hash, file } => {
            Some(format!("echo '{} {}' | {}sum -c", hash, file, algo))
        }
        Operation::Extract { file, dest, strip } => match strip {
            Some(n) => Some(format!(
                "tar -C {} -xf {} --strip-components={}",
                dest, file, n
            )),
            None => Some(format!("tar -C {} -xf {}", dest, file)),
        },
        Operation::Symlink { src, target } => Some(format!("ln -s {} {}", src, target)),
        Operation::DpkgInstall { file } => Some(format!("dpkg -i {}", file)),
        Operation::Run { cmd } => Some(cmd.clone()),
        Operation::VerifyGpg { file, sig } => Some(format!("gpg --verify {} {}", sig, file)),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_operation_to_chroot_apt_install() {
        let op = Operation::AptInstall {
            packages: vec!["wget".into(), "gpg".into()],
        };
        assert_eq!(
            operation_to_chroot(&op),
            Some("apt install -y wget gpg".to_string())
        );
    }

    #[test]
    fn test_operation_to_chroot_download() {
        let op = Operation::Download {
            url: "https://example.com/file".into(),
            dest: "/tmp/file".into(),
        };
        assert_eq!(
            operation_to_chroot(&op),
            Some("wget -q -O /tmp/file https://example.com/file".to_string())
        );
    }

    #[test]
    fn test_operation_to_chroot_run() {
        let op = Operation::Run {
            cmd: "go version".into(),
        };
        assert_eq!(operation_to_chroot(&op), Some("go version".to_string()));
    }

    #[test]
    fn test_operation_to_chroot_non_runtime() {
        assert_eq!(operation_to_chroot(&Operation::Sbuild), None);
        assert_eq!(operation_to_chroot(&Operation::Patch), None);
    }
}
