[package]
name = "hello-world-c"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "hello-world-c.sss"

[source]
type = "tarball"
url = "hello-world-1.0.0.tar.gz"
hash = "c93bdd829eca65af1e303d4a0b31cde0c3d3c2003fa1ca985393c412264b42c3b30c7893eb1d49ea654ca4f68269c30b3cca3db66d6b112f2be14f54c3d0edff"

[build]
distribution = "trixie"
arch = "amd64"
workdir = "~/.pkg-builder/packages/trixie"

[testing]
lintian = true
piuparts = true
autopkgtest = true

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.28"

[verify]
package_hash = [
    { name = "hello-world-c_1.0.0-1.dsc", hash = "ff308a118c1f71fa3c639f2dda197843878cbc17" },
    { name = "hello-world-c_1.0.0-1_amd64.deb", hash = "6611dc8d841a3fda9ce8d96274f6be8903a3a20a" },
]
