[package]
name = "hello-world-javascript"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "hello-world-javascript.sss"

[source]
type = "tarball"
url = "hello-world-javascript-1.0.0.tar.gz"
hash = "a7c7eb7779e319cc9c884128a64bd0997481c16aab75824b7f6a02844f847cbc46c5a04a21efcb024661ed0795fe9908fd8c00954ffdbff80337dcb6471d53f0"

[build]
distribution = "bookworm"
arch = "amd64"
workdir = "~/.pkg-builder/packages/bookworm"

[runtime]
recipe = "node"
binary_url = "https://nodejs.org/download/release/v20.12.2/node-v20.12.2-linux-x64.tar.gz"
binary_checksum = "f8f9b6877778ed2d5f920a5bd853f0f8a8be1c42f6d448c763a95625cbbb4b0d"
yarn_version = "1.22.19"

[testing]
lintian = true
piuparts = true
autopkgtest = true

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.28"

[verify]
package_hash = [
    { name = "hello-world-javascript_1.0.0-1.dsc", hash = "a6f9f4193ae180ac98f7832fc48aea8ea4fd9b2e78db819ef466e5d058f50c0f" },
    { name = "hello-world-javascript_1.0.0-1_amd64.deb", hash = "58f4804b1d3347e785a7fbda33a79f9b431c60fc18ce7cdd9f84b1d70b081de9" },
]
