[package]
name = "debian"
version = "0.1.0"
edition = "2021"

[lib]
name = "debian"
path = "src/mod.rs"

[dependencies]
types = { workspace = true }
log = { workspace = true }
shellexpand = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
