[package]
name = "debian"
version = "0.1.0"
edition = "2021"

[lib]
name = "debian"
path = "src/mod.rs"  

[dependencies]
common = { path = "../common" }
log = "0.4"
shellexpand = "3.1.0"
thiserror = "1.0"
