[package]
name = "hello-world-nim"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "hello-world-nim.sss"

[source]
type = "tarball"
url = "hello-world-nim-1.0.0.tar.gz"
hash = "b24e4ff701d8cbccab0cc78f2de55518babcd05a861af8d5d140863637b0ec74ba3ed5255bafc7fbe596defcc227e8f788c1e540655725eeabb7144be573e8a7"

[build]
distribution = "noble numbat"
arch = "amd64"
workdir = "~/.pkg-builder/packages/noble"

[runtime]
recipe = "nim"
binary_url = "https://nim-lang.org/download/nim-2.0.2-linux_x64.tar.xz"
binary_checksum = "047dde8ff40b18628ac1188baa9ca992d05f1f45c5121d1d07a76224f06e1551  nim-2.0.2-linux_x64.tar.xz"
nim_version = "2.0.2"

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"

[verify]
package_hash = [
    { name = "hello-world-nim_1.0.0-1.dsc", hash = "2383682bc8d608e920f39e6e7b0896118d4173e566accc46a2e781bd6e146490" },
    { name = "hello-world-nim_1.0.0-1_amd64.deb", hash = "29d6d3072a5d7fe6e0a21e4e1007409db1af89632132cb2a736d20619e7cd501" },
]
