[package]
name = "hello-world-java"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec_file = "hello-world-java.sss"

[source]
type = "tarball"
url = "hello-world-java-1.0.0.tar.gz"
hash = "c361ad7853f4eb1e272eb10fe70ac8a5fd40677da5d23e205e1808f2c6f3bed7"

[build]
distribution = "trixie"
arch = "amd64"
workdir = "~/.pkg-builder/packages"

[runtime]
recipe = "java"
binary_url = "https://download.oracle.com/java/17/archive/jdk-17.0.10_linux-x64_bin.tar.gz"
binary_checksum = "e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"

[testing]
lintian = true
piuparts = true
autopkgtest = true

[tools]
pkg_builder = "0.3.1"
sbuild = "0.85.6"
lintian = "2.116.3"
piuparts = "1.1.7"
autopkgtest = "5.28"
