[verify]
package_hash=[
    { hash="a59da8a216ca0cb291b2eb0fb24f26beb22b86fe", name= "hello-world-java-gradle_1.0.0-1.dsc"},
    { hash="eef991395fabb27016cc1a2e37cbaa04fd869de8", name= "hello-world-java-gradle_1.0.0.orig.tar.gz"},
    { hash="cd3bec7ec76c3344ce4b9f6ec34c9895aa633599", name= "hello-world-java-gradle_1.0.0-1.debian.tar.xz"},
    { hash="a09043df4d893fcf5c50134e3b1e97bc040f10a4", name= "hello-world-java-gradle_1.0.0-1_amd64.deb"},
]