[package_fields]
spec_file = "hello-world-dotnet.sss"
package_name = "hello-world-dotnet"
version_number = "1.0.0"
revision_number = "1"
homepage="https://github.com/eth-pkg/pkg-builder#examples"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "hello-world-dotnet-1.0.0.tar.gz"
tarball_hash = "f263892f5ed6cbcd82f31d60058eed359686d7e745c3da97fea917ee2f44867c4db9bd374f224e89e6efc7ffad4eadb244eefe7c95d25983f8a5a4086dadb78d"

[package_type.language_env]
language_env = "dotnet"
dotnet_version = "8.0"
dotnet_full_version = "8.0.204-1"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.2.2"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/bookworm"


[verify]
# if tarball_url is specified
tarball_hash=""
# if git_source is specified and package_is_git
git_commit=""
# output hash
bin_bash=""