[package_fields]
spec_file = "hello-world-java-gradle.sss"
package_name = "hello-world-java-gradle"
version_number = "1.0.0"
revision_number = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "hello-world-java-gradle-1.0.0.tar.gz"
tarball_hash = "9838986aeb5fbf1e24fc20da08772c2264b5e0ace8a09b423c39cdc8774b0c04"

[package_type.language_env]
language_env = "java"
is_oracle=true
jdk_version="17.0"
jdk_binary_url="https://download.oracle.com/java/17/archive/jdk-17.0.10_linux-x64_bin.tar.gz"
jdk_binary_checksum="e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"

[package_type.language_env.gradle]
gradle_version="8.7"
gradle_binary_url="https://github.com/gradle/gradle-distributions/releases/download/v8.7.0/gradle-8.7-bin.zip"
gradle_binary_checksum="544c35d6bd849ae8a5ed0bcea39ba677dc40f49df7d1835561582da2009b961d"

[build_env]
codename="jammy jellyfish"
arch = "amd64"
pkg_builder_version="0.2.3"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.20"
sbuild_version="0.85.6"
# package directory
workdir = "~/.pkg-builder/packages"
