[package]
name = "hello-world-c"
version = "1.0.0"
revision = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"
spec = "hello-world-c.sss"

[source]
type = "tarball"
url = "hello-world-1.0.0.tar.gz"
hash = "c93bdd829eca65af1e303d4a0b31cde0c3d3c2003fa1ca985393c412264b42c3b30c7893eb1d49ea654ca4f68269c30b3cca3db66d6b112f2be14f54c3d0edff"

[build]
distribution = "bookworm"
arch = "amd64"
workdir = "~/.pkg-builder/packages/bookworm"

[tools]
pkg_builder = "0.3.1"
debcrafter = "8189263"
sbuild = "0.85.6"

[verify]
package_hash = [
    { name = "hello-world-c_1.0.0-1.dsc", hash = "f0131a2e588dcbbabf3258f16ddceedca9a0f9e6ce9d49667992b4a5a5d96c46" },
    { name = "hello-world-c_1.0.0-1_amd64.deb", hash = "ddaca84a08136ae206b94d3c5a0d6e03839e9063a3e78954e3bd942ebb54fda5" },
]
