name: 'Run Packaging Tests'
description: 'Runs the packaging tests'

inputs:
  distro:
    description: 'Distribution to test (bookworm, trixie, noble)'
    required: true
  language:
    description: 'Language to test'
    required: true
  run_piuparts:
    description: 'Whether to run piuparts'
    required: false
    default: 'false'
  run_autopkgtest:
    description: 'Whether to run autopkgtest'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        cd examples/${{ inputs.distro }}/${{ inputs.language }}/hello-world
        pkg-builder --install-deps build

    - name: Piuparts
      if: ${{ inputs.run_piuparts == 'true' }}
      shell: bash
      run: |
        cd examples/${{ inputs.distro }}/${{ inputs.language }}/hello-world
        pkg-builder test piuparts

    - name: Autopkgtest
      if: ${{ inputs.run_autopkgtest == 'true' }}
      shell: bash
      run: |
        cd examples/${{ inputs.distro }}/${{ inputs.language }}/hello-world
        pkg-builder test autopkgtest

    - name: Verify
      shell: bash
      run: |
        cd examples/${{ inputs.distro }}/${{ inputs.language }}/hello-world
        pkg-builder verify
