name: 'Run Packaging Tests'
description: 'Runs the packaging tests'

inputs:
  distro:
    description: 'Distribution to test (bookworm, trixie, noble)'
    required: true
  language:
    description: 'Language to test'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        cd examples/${{ inputs.distro }}/${{ inputs.language }}/hello-world
        pkg-builder --install-deps build --with-tests

    - name: Verify
      shell: bash
      run: |
        cd examples/${{ inputs.distro }}/${{ inputs.language }}/hello-world
        pkg-builder verify
