use std::path::Path;

/// Test that all example configs generate Makefiles without errors.
fn generate_for(example_dir: &str) {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("examples")
        .join(example_dir);

    let config = config::PkgConfig::load(&path).unwrap_or_else(|e| {
        panic!("Failed to load config at {:?}: {}", path, e);
    });

    let makefile = makefile::generate(&config).unwrap_or_else(|e| {
        panic!("Failed to generate Makefile for {:?}: {}", path, e);
    });

    // Basic sanity checks
    assert!(makefile.contains("# Auto-generated by pkg-builder"));
    assert!(makefile.contains(".PHONY:"));
    assert!(makefile.contains("sbuild:") || makefile.contains("sbuild \\"));
    assert!(makefile.contains("clean:"));
}

// Bookworm
#[test] fn gen_bookworm_c() { generate_for("bookworm/c/hello-world"); }
#[test] fn gen_bookworm_go() { generate_for("bookworm/go/hello-world"); }
#[test] fn gen_bookworm_rust() { generate_for("bookworm/rust/hello-world"); }
#[test] fn gen_bookworm_python() { generate_for("bookworm/python/hello-world"); }
#[test] fn gen_bookworm_java() { generate_for("bookworm/java/hello-world"); }
#[test] fn gen_bookworm_java_gradle() { generate_for("bookworm/java-gradle/hello-world"); }
#[test] fn gen_bookworm_javascript() { generate_for("bookworm/javascript/hello-world"); }
#[test] fn gen_bookworm_typescript() { generate_for("bookworm/typescript/hello-world"); }
#[test] fn gen_bookworm_nim() { generate_for("bookworm/nim/hello-world"); }
#[test] fn gen_bookworm_dotnet() { generate_for("bookworm/dotnet/hello-world"); }
#[test] fn gen_bookworm_virtual() { generate_for("bookworm/virtual/hello-world"); }
#[test] fn gen_bookworm_git() { generate_for("bookworm/git-package/nimbus"); }

// Noble
#[test] fn gen_noble_c() { generate_for("noble/c/hello-world"); }
#[test] fn gen_noble_go() { generate_for("noble/go/hello-world"); }
#[test] fn gen_noble_rust() { generate_for("noble/rust/hello-world"); }
#[test] fn gen_noble_python() { generate_for("noble/python/hello-world"); }
#[test] fn gen_noble_java() { generate_for("noble/java/hello-world"); }
#[test] fn gen_noble_java_gradle() { generate_for("noble/java-gradle/hello-world"); }
#[test] fn gen_noble_javascript() { generate_for("noble/javascript/hello-world"); }
#[test] fn gen_noble_typescript() { generate_for("noble/typescript/hello-world"); }
#[test] fn gen_noble_nim() { generate_for("noble/nim/hello-world"); }
#[test] fn gen_noble_dotnet() { generate_for("noble/dotnet/hello-world"); }
#[test] fn gen_noble_dotnet9() { generate_for("noble/dotnet-9/hello-world"); }
#[test] fn gen_noble_virtual() { generate_for("noble/virtual/hello-world"); }
#[test] fn gen_noble_git() { generate_for("noble/git-package/nimbus"); }

// Trixie
#[test] fn gen_trixie_c() { generate_for("trixie/c/hello-world"); }
#[test] fn gen_trixie_go() { generate_for("trixie/go/hello-world"); }
#[test] fn gen_trixie_rust() { generate_for("trixie/rust/hello-world"); }
#[test] fn gen_trixie_python() { generate_for("trixie/python/hello-world"); }
#[test] fn gen_trixie_java() { generate_for("trixie/java/hello-world"); }
#[test] fn gen_trixie_java_gradle() { generate_for("trixie/java-gradle/hello-world"); }
#[test] fn gen_trixie_javascript() { generate_for("trixie/javascript/hello-world"); }
#[test] fn gen_trixie_typescript() { generate_for("trixie/typescript/hello-world"); }
#[test] fn gen_trixie_nim() { generate_for("trixie/nim/hello-world"); }
#[test] fn gen_trixie_dotnet() { generate_for("trixie/dotnet/hello-world"); }
#[test] fn gen_trixie_virtual() { generate_for("trixie/virtual/hello-world"); }
#[test] fn gen_trixie_git() { generate_for("trixie/git-package/nimbus"); }

// Jammy
#[test] fn gen_jammy_c() { generate_for("jammy/c/hello-world"); }
#[test] fn gen_jammy_go() { generate_for("jammy/go/hello-world"); }
#[test] fn gen_jammy_rust() { generate_for("jammy/rust/hello-world"); }
#[test] fn gen_jammy_java() { generate_for("jammy/java/hello-world"); }
#[test] fn gen_jammy_java_gradle() { generate_for("jammy/java-gradle/hello-world"); }
#[test] fn gen_jammy_javascript() { generate_for("jammy/javascript/hello-world"); }
#[test] fn gen_jammy_typescript() { generate_for("jammy/typescript/hello-world"); }
#[test] fn gen_jammy_nim() { generate_for("jammy/nim/hello-world"); }
#[test] fn gen_jammy_dotnet() { generate_for("jammy/dotnet/hello-world"); }
#[test] fn gen_jammy_virtual() { generate_for("jammy/virtual/hello-world"); }
#[test] fn gen_jammy_git() { generate_for("jammy/git-package/nimbus"); }

/// Test that Noble examples have extra repos in the generated Makefile.
#[test]
fn test_noble_has_extra_repos() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap().parent().unwrap()
        .join("examples/noble/go/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let makefile = makefile::generate(&config).unwrap();
    assert!(makefile.contains("add-apt-repository universe"));
    assert!(makefile.contains("add-apt-repository multiverse"));
}

/// Test that virtual packages don't have runtime commands.
#[test]
fn test_virtual_no_runtime() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap().parent().unwrap()
        .join("examples/bookworm/virtual/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let makefile = makefile::generate(&config).unwrap();
    // Should not have wget or language-specific commands
    assert!(!makefile.contains("go version"));
    assert!(!makefile.contains("rustc"));
}

/// Test that Go example has expected chroot commands.
#[test]
fn test_go_has_chroot_commands() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap().parent().unwrap()
        .join("examples/bookworm/go/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let makefile = makefile::generate(&config).unwrap();
    assert!(makefile.contains("go version"));
    assert!(makefile.contains("chmod -R a+rwx /usr/local/go/pkg"));
    assert!(makefile.contains("ln -s /usr/local/go/bin/go /usr/bin/go"));
}

/// Test that dotnet REPEAT expands all packages.
#[test]
fn test_dotnet_repeat_expanded() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap().parent().unwrap()
        .join("examples/noble/dotnet/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let makefile = makefile::generate(&config).unwrap();
    assert!(makefile.contains("dotnet --version"));
    // Should have multiple dpkg -i lines for each package
    let dpkg_count = makefile.matches("dpkg -i").count();
    assert!(dpkg_count > 5, "Expected many dpkg -i, got {}", dpkg_count);
}
