use std::path::Path;

/// Test that all example configs generate Makefiles and sbuild.conf without errors.
fn generate_for(example_dir: &str) {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("examples")
        .join(example_dir);

    let config = config::PkgConfig::load(&path).unwrap_or_else(|e| {
        panic!("Failed to load config at {:?}: {}", path, e);
    });

    let output = makefile::generate(&config).unwrap_or_else(|e| {
        panic!("Failed to generate for {:?}: {}", path, e);
    });

    // Basic Makefile sanity checks
    assert!(output.makefile.contains("# Auto-generated by pkg-builder"));
    assert!(output.makefile.contains(".PHONY:"));
    assert!(
        output.makefile.contains("sbuild:") || output.makefile.contains("sbuild build:")
    );
    assert!(output.makefile.contains("clean:"));

    // Makefile should use SBUILD_CONFIG, not SBUILD_FLAGS
    assert!(
        output.makefile.contains("SBUILD_CONFIG="),
        "Expected SBUILD_CONFIG in Makefile for {}",
        example_dir
    );
    assert!(
        !output.makefile.contains("SBUILD_FLAGS"),
        "SBUILD_FLAGS should not appear in Makefile for {}",
        example_dir
    );

    // Basic sbuild.conf sanity checks
    assert!(output.sbuild_conf.contains("$distribution"));
    assert!(output.sbuild_conf.contains("$chroot_mode = 'unshare'"));
    assert!(output.sbuild_conf.contains("1;"));
}

// Bookworm
#[test]
fn gen_bookworm_c() {
    generate_for("bookworm/c/hello-world");
}
#[test]
fn gen_bookworm_go() {
    generate_for("bookworm/go/hello-world");
}
#[test]
fn gen_bookworm_rust() {
    generate_for("bookworm/rust/hello-world");
}
#[test]
fn gen_bookworm_java() {
    generate_for("bookworm/java/hello-world");
}
#[test]
fn gen_bookworm_java_gradle() {
    generate_for("bookworm/java-gradle/hello-world");
}
#[test]
fn gen_bookworm_javascript() {
    generate_for("bookworm/javascript/hello-world");
}
#[test]
fn gen_bookworm_typescript() {
    generate_for("bookworm/typescript/hello-world");
}
#[test]
fn gen_bookworm_nim() {
    generate_for("bookworm/nim/hello-world");
}
#[test]
fn gen_bookworm_dotnet() {
    generate_for("bookworm/dotnet/hello-world");
}
#[test]
fn gen_bookworm_virtual() {
    generate_for("bookworm/virtual/hello-world");
}
#[test]
fn gen_bookworm_git() {
    generate_for("bookworm/git-package/nimbus");
}

// Noble
#[test]
fn gen_noble_c() {
    generate_for("noble/c/hello-world");
}
#[test]
fn gen_noble_go() {
    generate_for("noble/go/hello-world");
}
#[test]
fn gen_noble_rust() {
    generate_for("noble/rust/hello-world");
}
#[test]
fn gen_noble_java() {
    generate_for("noble/java/hello-world");
}
#[test]
fn gen_noble_java_gradle() {
    generate_for("noble/java-gradle/hello-world");
}
#[test]
fn gen_noble_javascript() {
    generate_for("noble/javascript/hello-world");
}
#[test]
fn gen_noble_typescript() {
    generate_for("noble/typescript/hello-world");
}
#[test]
fn gen_noble_nim() {
    generate_for("noble/nim/hello-world");
}
#[test]
fn gen_noble_dotnet() {
    generate_for("noble/dotnet/hello-world");
}
#[test]
fn gen_noble_dotnet9() {
    generate_for("noble/dotnet-9/hello-world");
}
#[test]
fn gen_noble_virtual() {
    generate_for("noble/virtual/hello-world");
}
#[test]
fn gen_noble_git() {
    generate_for("noble/git-package/nimbus");
}

// Trixie
#[test]
fn gen_trixie_c() {
    generate_for("trixie/c/hello-world");
}
#[test]
fn gen_trixie_go() {
    generate_for("trixie/go/hello-world");
}
#[test]
fn gen_trixie_rust() {
    generate_for("trixie/rust/hello-world");
}
#[test]
fn gen_trixie_java() {
    generate_for("trixie/java/hello-world");
}
#[test]
fn gen_trixie_java_gradle() {
    generate_for("trixie/java-gradle/hello-world");
}
#[test]
fn gen_trixie_javascript() {
    generate_for("trixie/javascript/hello-world");
}
#[test]
fn gen_trixie_typescript() {
    generate_for("trixie/typescript/hello-world");
}
#[test]
fn gen_trixie_nim() {
    generate_for("trixie/nim/hello-world");
}
#[test]
fn gen_trixie_dotnet() {
    generate_for("trixie/dotnet/hello-world");
}
#[test]
fn gen_trixie_virtual() {
    generate_for("trixie/virtual/hello-world");
}
#[test]
fn gen_trixie_git() {
    generate_for("trixie/git-package/nimbus");
}

/// Test that Noble examples have extra repos in sbuild.conf.
#[test]
fn test_noble_has_extra_repos() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("examples/noble/go/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let output = makefile::generate(&config).unwrap();
    assert!(output.sbuild_conf.contains("add-apt-repository universe"));
    assert!(output.sbuild_conf.contains("add-apt-repository multiverse"));
}

/// Test that virtual packages don't have runtime commands.
#[test]
fn test_virtual_no_runtime() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("examples/bookworm/virtual/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let output = makefile::generate(&config).unwrap();
    // Should not have language-specific commands in sbuild.conf
    assert!(!output.sbuild_conf.contains("go version"));
    assert!(!output.sbuild_conf.contains("rustc"));
}

/// Test that Go example has expected chroot commands in sbuild.conf.
#[test]
fn test_go_has_chroot_commands() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("examples/bookworm/go/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let output = makefile::generate(&config).unwrap();
    assert!(output.sbuild_conf.contains("go version"));
    assert!(output.sbuild_conf.contains("chmod -R a+rwx /usr/local/go/pkg"));
    assert!(output.sbuild_conf.contains("ln -s /usr/local/go/bin/go /usr/bin/go"));
    // Variables should be substituted with actual values
    assert!(output.sbuild_conf.contains("go.dev/dl/go1.22.2"));
    assert!(output.sbuild_conf.contains("5901c52b"));
}

/// Test that dotnet packages are expanded with actual package values.
#[test]
fn test_dotnet_repeat_expanded() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("examples/noble/dotnet/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let output = makefile::generate(&config).unwrap();
    assert!(output.sbuild_conf.contains("dotnet --version"));
    // Should have actual package names (not Make variables)
    assert!(
        output.sbuild_conf.contains("netstandard-targeting-pack"),
        "Expected actual package name in sbuild.conf"
    );
    // Should NOT have Make variable references
    assert!(
        !output.sbuild_conf.contains("$(PKG"),
        "Should not have Make variable references in sbuild.conf"
    );
    // Should NOT have $(foreach) — that's a Make construct
    assert!(
        !output.sbuild_conf.contains("$(foreach"),
        "Should not have $(foreach) in sbuild.conf"
    );
}

/// Test that sbuild.conf has lintian settings when enabled.
#[test]
fn test_sbuild_conf_lintian_disabled_always() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("examples/bookworm/go/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    let output = makefile::generate(&config).unwrap();
    assert!(output.sbuild_conf.contains("$run_lintian = 0"));
    assert!(!output.sbuild_conf.contains("$lintian_opts"));
}

/// Test that sbuild.conf disables lintian when not configured.
#[test]
fn test_sbuild_conf_lintian_disabled() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("examples/bookworm/virtual/hello-world");
    let config = config::PkgConfig::load(&path).unwrap();
    // Virtual example has lintian enabled, but let's check the conf is generated
    let output = makefile::generate(&config).unwrap();
    assert!(output.sbuild_conf.contains("$run_lintian"));
}
