name: 'Setup sbuild'
description: 'Installs sbuild and its dependencies'

runs:
  using: "composite"
  steps:
    - name: Install sbuild and dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper schroot ubuntu-dev-tools \
          pkg-config libssl-dev uidmap \
          libfilesys-df-perl libmime-lite-perl
        wget -q https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6-1/sbuild_0.85.6_all.deb
        wget -q https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6-1/libsbuild-perl_0.85.6_all.deb
        sudo dpkg -i sbuild_0.85.6_all.deb libsbuild-perl_0.85.6_all.deb || true
        sudo sbuild-adduser $(whoami)
