name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'    
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup sbuild
        uses: ./.github/actions/setup-sbuild

      - name: Build
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --lib --verbose -- --ignored

  bookworm:
    uses: ./.github/workflows/packaging.yml
    with:
      distro: bookworm
      languages: |
        - c
        - dotnet
        - go
        - java
        - java-gradle
        - javascript
        - nim
        - rust
        - typescript
        - virtual

  # trixie:
  #   uses: ./.github/workflows/packaging.yml
  #   with:
  #     distro: trixie
  #     languages: |
  #       - c

  noble:
    uses: ./.github/workflows/packaging.yml
    with:
      distro: noble
      languages: |
        - c
      include_genisoimage: true

  # jammy:
  #   uses: ./.github/workflows/packaging.yml
  #   with:
  #     distro: jammy
  #     languages: |
  #       - c
  #       - dotnet
  #       - go
  #       - java
  #       - java-gradle
  #       - javascript
  #       - nim
  #       - rust
  #       - typescript
  #       - virtual
